- docs/certificates.md
Add a section how to use pre-existing CA for openstack endpoints
Fix  https://github.com/vexxhost/atmosphere/issues/31
> [Doc] Update certificates doc

- roles/openstack_exporter/defaults/main.yml
- roles/openstack_exporter/tasks/main.yml
Fixes https://github.com/vexxhost/atmosphere/issues/44
> fix: switch openstack-exporter to new image repo

- internal/pkg/image_repositories/build_workflow.go
- internal/pkg/image_repositories/dockerfile.go
- roles/openstack_helm_glance/tasks/main.yml
- roles/openstack_helm_glance/vars/main.yml
- Fixes https://github.com/vexxhost/atmosphere/issues/47
- Fixes https://github.com/vexxhost/atmosphere/issues/48
- Fixes https://github.com/vexxhost/atmosphere/issues/46
> Fix Glance with Cinder backend

- roles/openstack_helm_nova/vars/main.yml
Reverts vexxhost/atmosphere#95
> Revert "Switch to use vnc_lite instead of vnc_auto"

- atmosphere/flows.py
- atmosphere/models/config.py
- atmosphere/tasks/composite/openstack_helm.py
- atmosphere/tasks/constants.py
- atmosphere/tasks/kubernetes/cert_manager.py
- atmosphere/tests/unit/tasks/composite/test_openstack_helm.py
- atmosphere/tests/unit/tasks/kubernetes/test_cert_manager.py
- docs/components/ingress.md
> feat(ingress): enable overriding/disabling

- roles/openstack_helm_glance/vars/main.yml
> [role:glance] Update worker number as 8

- roles/openstack_helm_glance/tasks/main.yml
- roles/openstack_helm_infra_openvswitch/tasks/main.yml
- roles/openstack_helm_neutron/tasks/main.yml
> fix: bump osh for ovs fixes

- atmosphere/flows.py
- atmosphere/models/config.py
- atmosphere/tasks/composite/openstack_helm.py
- atmosphere/tasks/constants.py
- atmosphere/tests/unit/tasks/composite/test_openstack_helm.py
- docs/integrations.md
This commit adds a native ingration for adding OpsGenie to the monitoring so you can easily and quickly have alerts go straight into OpsGenie.
Jira: ATMOSPHERE-75
> feat(opsgenie): add integration

- Dockerfile
- atmosphere/cmd/operator.py
- atmosphere/operator/api/openstack/identity.py
- atmosphere/operator/controllers/__init__.py
- atmosphere/operator/controllers/openstack/__init__.py
- atmosphere/operator/controllers/openstack/identity/__init__.py
- atmosphere/operator/controllers/openstack/identity/endpoint.py
- atmosphere/operator/controllers/openstack/identity/implied_role.py
- atmosphere/operator/controllers/openstack/identity/role.py
- atmosphere/operator/controllers/openstack/identity/service.py
- atmosphere/operator/controllers/openstack/utils.py
- atmosphere/operator/controllers/utils.py
- atmosphere/tests/e2e/test_operator.py
- poetry.lock
- pyproject.toml
- roles/atmosphere/tasks/main.yml
- roles/atmosphere/templates/cluster_role.yml
- roles/atmosphere/templates/crds.yml
- roles/atmosphere/templates/deployment.yml
- roles/atmosphere/templates/resources.yml
> feat: add endpoint, implied_role, role & service

- internal/pkg/image_repositories/build_workflow.go
> chore: bump magnum-cluster-api

- .github/workflows/test.yml
> chore: Increase molecule CI job timeout

- docs/quick-start.md
1) added step to install poetry dependencies
> chore: refactor quickstart docs

- roles/defaults/defaults/main.yml
- roles/magnum/defaults/main.yml
- roles/magnum/tasks/main.yml
Reverts vexxhost/atmosphere#347
> Revert "feat: override CAPO"

- charts/horizon/Chart.yaml
- charts/horizon/charts/helm-toolkit/Chart.yaml
- charts/horizon/charts/helm-toolkit/templates/scripts/db-backup-restore/_backup_main.sh.tpl
- charts/horizon/requirements.lock
- charts/horizon/templates/bin/_horizon.sh.tpl
- charts/horizon/templates/deployment.yaml
- charts/horizon/values.yaml
- hack/sync-charts.sh
To enable manila_ui extra panel
> chore: Apply uptream patch for horizon osh chart

- charts/barbican/requirements.lock
- charts/barbican/templates/configmap-etc.yaml
- charts/cinder/requirements.lock
- charts/designate/requirements.lock
- charts/glance/requirements.lock
- charts/heat/requirements.lock
- charts/horizon/requirements.lock
- charts/magnum/requirements.lock
- charts/manila/requirements.lock
- charts/nova/requirements.lock
- charts/senlin/requirements.lock
- charts/tempest/requirements.lock
- hack/sync-charts.sh
fix https://github.com/vexxhost/atmosphere/issues/431
> fix: Fix barbican the paste api paste config path for uwsgi

- roles/defaults/defaults/main.yml
https://github.com/vexxhost/atmosphere/issues/431
> chore: update magnum image tags

- .github/workflows/ceph.yml
> fix(ci): Run tmate session onlyl starts if a previous step failed

- docs/admin/ingress.md
The dollar sign makes markdownlint a bit unhappy, let's use sh and remove the dollar sign to unblock gate
> fix lint issue

- galaxy.yml
- roles/magnum/defaults/main.yml
- roles/magnum/meta/main.yml
- roles/magnum/tasks/main.yml
> chore: refactor to using v.k.cluster_api

- charts/designate/requirements.lock
- charts/magnum/requirements.lock
- charts/neutron/requirements.lock
- charts/pxc-operator/Chart.yaml
- charts/pxc-operator/README.md
- charts/pxc-operator/crds/crd.yaml
- charts/pxc-operator/templates/NOTES.txt
- charts/pxc-operator/templates/deployment.yaml
- charts/pxc-operator/templates/role.yaml
- charts/pxc-operator/values.yaml
- charts/senlin/requirements.lock
- charts/tempest/requirements.lock
- hack/sync-charts.sh
- roles/defaults/vars/main.yml
- roles/percona_xtradb_cluster/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/463
> chore(role:pxco): Bump percona-xtradb-cluster-operator version to 1.12

- galaxy.yml
> chore: bump vexxhost.atmosphere.kubernetes

- internal/pkg/image_repositories/build_workflow.go
Reverts vexxhost/atmosphere#507 as we will move staffeln image build to itself
> Revert "Allows image repositories builds staffeln image"

- roles/nova/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/513
> Remove nova-cell-setup job

- charts/designate/requirements.lock
- charts/magnum/requirements.lock
- charts/octavia/Chart.yaml
- charts/octavia/requirements.lock
- charts/octavia/values.yaml
- charts/senlin/requirements.lock
- charts/tempest/requirements.lock
- docs/admin/compute.md
- hack/sync-charts.sh
fix https://github.com/vexxhost/atmosphere/issues/519
> Honoring default configs for haproxy_amphora

- charts/cinder/Chart.yaml
- charts/cinder/charts/helm-toolkit/Chart.yaml
- charts/cinder/charts/helm-toolkit/templates/utils/_dependency_resolver.tpl
- charts/cinder/requirements.lock
- charts/cinder/values.yaml
- charts/neutron/templates/bin/_neutron-netns-cleanup-cron.py.tpl
- charts/placement/Chart.yaml
- charts/placement/charts/helm-toolkit/Chart.yaml
- charts/placement/charts/helm-toolkit/templates/scripts/_db-init.py.tpl
- charts/placement/charts/helm-toolkit/templates/utils/_dependency_resolver.tpl
- charts/placement/requirements.lock
- charts/placement/values.yaml
- charts/placement/values_overrides/2023.1-ubuntu_focal.yaml
- charts/placement/values_overrides/zed-ubuntu_focal.yaml
- hack/sync-charts.sh
fix https://github.com/vexxhost/atmosphere/issues/529
> fix: CVE-2023-2088: Use service tokens

- .github/workflows/image-manifest.yml
- roles/keycloak/tasks/main.yml
This includes:
* Use larger disk space for image-manifest
fix: https://github.com/vexxhost/atmosphere/issues/643
fix: https://github.com/vexxhost/atmosphere/issues/648
> fix(CI): image-manifest and ceph(ovs/ovn)

- roles/percona_xtradb_cluster/vars/main.yml
> Fix: Disable in percona name resolution

- roles/neutron/vars/main.yml
- roles/nova/vars/main.yml
fix: https://github.com/vexxhost/atmosphere/issues/636
> Fix(nova, neutron): specify missing region name

- roles/defaults/vars/main.yml
Closes https://github.com/vexxhost/atmosphere/issues/566
> feat(ovs): bump ovs to 3.x

- roles/keycloak/vars/main.yml
fix https://github.com/vexxhost/atmosphere/issues/580
> fix(keycloak): Run on control plane

- roles/defaults/vars/main.yml
Closes: https://github.com/vexxhost/atmosphere/issues/659
> fix(ovs): bump to 3.1.0-55atmosphere1

- roles/defaults/vars/main.yml
fix https://github.com/vexxhost/atmosphere/issues/621
fix https://github.com/vexxhost/atmosphere/issues/505
> chore(horizon): bump image version

- charts/nova/Chart.yaml
- charts/nova/charts/helm-toolkit/Chart.yaml
- charts/nova/charts/helm-toolkit/templates/manifests/_ingress.tpl
- charts/nova/requirements.lock
- charts/nova/templates/bin/_nova-compute.sh.tpl
- charts/nova/templates/configmap-etc.yaml
- charts/nova/values.yaml
- hack/sync-charts.sh
relate to https://github.com/vexxhost/atmosphere/issues/681
> chore(nova): bump nova charts version

- charts/cinder/Chart.yaml
- charts/cinder/charts/helm-toolkit/Chart.yaml
- charts/cinder/charts/helm-toolkit/templates/manifests/_ingress.tpl
- charts/cinder/requirements.lock
- charts/cinder/templates/bin/_cinder-api.sh.tpl
- hack/sync-charts.sh
relate: https://github.com/vexxhost/atmosphere/issues/681
> chore(cinder): bump cinder chart version

- roles/keystone/meta/main.yml
- roles/keystone/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/595
> fix: Avoid localhost delegation for openstack.cloud tasks

- charts/staffeln/values.yaml
Setting the values so that it backups only once a day.
> chore: staffeln values

- roles/manila/defaults/main.yml
- roles/manila/tasks/generate_resources.yml
- roles/octavia/defaults/main.yml
- roles/octavia/tasks/generate_resources.yml
fix: adding extra specs parameter to manila and octavia flavors for DPDK support
> fix: octavia and manila flavor extra specs 

- charts/nova/templates/daemonset-compute.yaml
- charts/nova/values.yaml
- hack/sync-charts.sh
upstream ref: https://review.opendev.org/c/openstack/openstack-helm/+/904250
fix https://github.com/vexxhost/atmosphere/issues/766
> fix: refactor nova-compute probes

- roles/keystone/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/764
> fix: increase the wait timeout for keystone ingress

- roles/defaults/vars/main.yml
https://github.com/vexxhost/neutron/pull/2
> chore: update neutorn image tag

- .github/dependabot.yml
- .github/renovate.json
- roles/defaults/vars/main.yml
- fix image names for renovate
- chore: test renovate config
- chore: added renovate.json
> chore: add renovate

- roles/keycloak/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/763
> fix: increase the wait timeout for keycloak helm chart deployment

- docs/user/networking.md
Documentation for an OVN and DPDK enabled network configuration.  Related to PR #773, PR #769, and PR #767
> docs: For OVN/DPDK config

- charts/cert-manager-webhook-godaddy/.helmignore
- charts/cert-manager-webhook-godaddy/Chart.yaml
- charts/cert-manager-webhook-godaddy/templates/_helpers.tpl
- charts/cert-manager-webhook-godaddy/templates/apiservice.yaml
- charts/cert-manager-webhook-godaddy/templates/deployment.yaml
- charts/cert-manager-webhook-godaddy/templates/pki.yaml
- charts/cert-manager-webhook-godaddy/templates/rbac.yaml
- charts/cert-manager-webhook-godaddy/templates/service.yaml
- charts/cert-manager-webhook-godaddy/values.yaml
- roles/cluster_issuer/README.md
- roles/cluster_issuer/defaults/main.yml
- roles/cluster_issuer/handlers/main.yml
- roles/cluster_issuer/tasks/main.yml
- roles/cluster_issuer/tasks/type/acme/solver/godaddy.yml
- roles/cluster_issuer/vars/main.yml
- vendir.lock.yml
- vendir.yml
Also small change to make EL distros happy with `update-ca-certificates`|`update-ca-trust`
> feat: add goddady webhook for cluster_issuer

- galaxy.yml
- roles/cluster_issuer/tasks/type/self-signed/main.yml
- roles/octavia/tasks/main.yml
Changelog: https://github.com/vexxhost/ansible-collection-kubernetes/compare/v1.10.0...v1.12.1
> chore(deps): Bump vexxhost.atmosphere.kubernetes 1.12.1

- .github/workflows/csi.yml
- galaxy.yml
- molecule/aio/converge.yml
- molecule/aio/molecule.yml
- molecule/aio/prepare.yml
- molecule/shared/molecule.yml
- playbooks/ceph.yml
- playbooks/csi.yml
- playbooks/kubernetes.yml
- playbooks/openstack.yml
- playbooks/site.yml
- roles/ceph_csi_rbd/tasks/main.yml
- roles/ceph_provisioners/tasks/main.yml
- roles/rook_ceph_cluster/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/711
> feat: adopt cephadm

- Earthfile
fix https://github.com/vexxhost/atmosphere/issues/1031
> fix: increase trivy timeout

- images/ovn/Earthfile
fix https://github.com/vexxhost/atmosphere/issues/1029
> fix: lock commit hash of ovn-kubernetes project for ovn image build

- charts/ovn/templates/statefulset-ovsdb-nb.yaml
- charts/ovn/templates/statefulset-ovsdb-sb.yaml
- hack/sync-charts.sh
fix https://github.com/vexxhost/atmosphere/issues/1040
https://review.opendev.org/c/openstack/openstack-helm-infra/+/914807
Depends-On: https://github.com/vexxhost/atmosphere/pull/1043
> fix: fix ovn db mount path

- roles/cinder/tasks/main.yml
- roles/cinder/vars/main.yml
- roles/defaults/vars/main.yml
- roles/kube_prometheus_stack/files/jsonnet/openstack.libsonnet
- roles/kube_prometheus_stack/vars/main.yml
- roles/openstack_exporter/meta/main.yml
- roles/openstack_exporter/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/1038
Depends-On: https://github.com/vexxhost/atmosphere/pull/1050
> feat: Add openstack db exporter

- Jenkinsfile
- images/barbican/Dockerfile
- images/openstack-runtime/Dockerfile
- images/openstack-venv-builder/Dockerfile
- images/requirements/Dockerfile
- images/ubuntu/Dockerfile
- zuul.d/jobs.yaml
- zuul.d/playbooks/build-images/run.yml
> ci: fix cache misses

- zuul.d/jobs.yaml
> ci: set ovn to non-voting

- Dockerfile
- docker-bake.hcl
- patches/zed/magnum/0000-Fix-Trust-token-scope-for-drivers.patch
- roles/defaults/vars/main.yml
> ci: build magnum images

- Earthfile
- build/pin-images.py
- tox.ini
- zuul.d/jobs.yaml
- zuul.d/playbooks/build-collection/pre.yml
- zuul.d/playbooks/build-collection/publish.yml
- zuul.d/playbooks/build-collection/run.yml
- zuul.d/project.yaml
- zuul.d/secrets.yaml
- **build: build all images + run tests using them (#1069)**
- **ci: fix promotion jobs (#1072)**
- **[stable/zed] Drop `conventional-commit` requirement (#1082)**
- **[stable/zed] fix(ipmi-exporter): Ignore additional sensor IDs (BP/Entity Presence) (#1077)**
- **Implement collection release process (#1083)**
> [stable/zed] Implement collection release process

- images/keepalived/Dockerfile
- roles/defaults/vars/main.yml
- zuul.d/container-images/keepalived.yaml
> Build `keepalived` image

- images/designate/Dockerfile
- images/designate/patches/designate/0000-Fix-Mysql-default-character-setting-utf8mb4.patch
This introduce DB fix from:
https://review.opendev.org/c/openstack/designate/+/910322
fix https://github.com/vexxhost/atmosphere/issues/985
> fix: add fix for designate db

- roles/barbican/tasks/main.yml
- roles/ceph_csi_rbd/tasks/main.yml
- roles/cert_manager/tasks/main.yml
- roles/cinder/tasks/main.yml
- roles/coredns/tasks/main.yml
- roles/designate/tasks/main.yml
- roles/glance/tasks/main.yml
- roles/heat/tasks/main.yml
- roles/horizon/tasks/main.yml
- roles/ingress_nginx/tasks/main.yml
- roles/keystone/tasks/main.yml
- roles/kube_prometheus_stack/tasks/main.yml
- roles/libvirt/tasks/main.yml
- roles/magnum/tasks/main.yml
- roles/memcached/tasks/main.yml
- roles/neutron/tasks/main.yml
- roles/node_feature_discovery/tasks/main.yml
- roles/nova/tasks/main.yml
- roles/octavia/tasks/main.yml
- roles/openvswitch/tasks/main.yml
- roles/percona_xtradb_cluster_operator/tasks/main.yml
- roles/placement/tasks/main.yml
- roles/prometheus_pushgateway/tasks/main.yml
- roles/rabbitmq_cluster_operator/tasks/main.yml
- roles/senlin/tasks/main.yml
> Remove FluxCD references

- images/cinder/Dockerfile
- images/cinder/patches/cinder/0001-Create-encrypted-volumes-directly-to-RBD.patch
- images/cinder/patches/cinder/0002-Allow-clone-encrypted-image-to-encrypted-volume.patch
- images/cinder/patches/cinder/0003-Allow-encrypted-volume-clone-from-Glance-image.patch
relate to https://github.com/vexxhost/atmosphere/issues/1016
> [stable/zed] chore: add cinder rbd tunning patches to zed

- .charts.yml
- charts/kube-prometheus-stack/Chart.lock
- charts/kube-prometheus-stack/Chart.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagerconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-alertmanagers.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-podmonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-probes.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusagents.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheuses.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-prometheusrules.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-scrapeconfigs.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-servicemonitors.yaml
- charts/kube-prometheus-stack/charts/crds/crds/crd-thanosrulers.yaml
- charts/kube-prometheus-stack/charts/grafana/Chart.yaml
- charts/kube-prometheus-stack/templates/_helpers.tpl
- charts/kube-prometheus-stack/templates/thanos-ruler/podDisruptionBudget.yaml
- charts/kube-prometheus-stack/templates/thanos-ruler/ruler.yaml
- charts/kube-prometheus-stack/templates/thanos-ruler/service.yaml
- charts/kube-prometheus-stack/values.yaml
- roles/defaults/vars/main.yml
This is needed to fix false positives for missing kube-scheduler, etc.
> Update kube-prometheus-stack to 58.1.3

- roles/ipmi_exporter/defaults/main.yml
Bad state on Dell PowerEdge M640.
> ipmi-exporter: Ignore sensor IDs 88/109/111 (Entity Presence)

- roles/horizon/defaults/main.yml
- roles/horizon/vars/main.yml
fix https://github.com/vexxhost/atmosphere/issues/727
> fix: correct keystone_domains reference from horizon

- roles/horizon/defaults/main.yml
- roles/horizon/vars/main.yml
Reverts vexxhost/atmosphere#992
> Revert "fix: correct keystone_domains reference from horizon"

- images/openstack-venv-builder/Dockerfile
Depends-On: https://github.com/vexxhost/atmosphere/pull/1266
> Build requirements from pinned Git hash

- doc/source/deploy/certificates.rst
- roles/cluster_issuer/defaults/main.yml
- roles/cluster_issuer/tasks/type/venafi/main.yml
- roles/openstack_cli/templates/atmosphere.sh.j2
- roles/openstack_cli/templates/openrc.j2
- roles/openstacksdk/templates/clouds.yaml.j2
> [stable/2023.1] Enable setting CA for Venafi

- doc/source/deploy/certificates.rst
- roles/cluster_issuer/defaults/main.yml
- roles/cluster_issuer/tasks/type/venafi/main.yml
- roles/openstack_cli/templates/atmosphere.sh.j2
- roles/openstack_cli/templates/openrc.j2
- roles/openstacksdk/templates/clouds.yaml.j2
> [stable/zed] Enable setting CA for Venafi

- playbooks/infrastructure.yml
- roles/cluster_issuer/tasks/main.yml
- roles/cluster_issuer/tasks/type/acme/solver/cloudflare.yml
- roles/cluster_issuer/tasks/type/acme/solver/http01.yml
- roles/cluster_issuer/tasks/type/acme/solver/rfc2136.yml
- roles/cluster_issuer/tasks/type/acme/solver/route53.yml
- roles/cluster_issuer/tasks/type/ca/main.yml
- roles/cluster_issuer/tasks/type/self-signed/main.yml
- roles/cluster_issuer/tasks/type/venafi/main.yml
- roles/defaults/defaults/main.yml
- roles/keepalived/tasks/main.yml
- roles/keycloak/tasks/main.yml
- roles/keystone/vars/main.yml
- roles/magnum/vars/main.yml
> [stable/zed] Mount CA into Keystone + Magnum

- doc/source/arch/images.rst
- doc/source/arch/index.rst
- doc/source/index.rst
> Add documentation about image builds

- playbooks/infrastructure.yml
- roles/cluster_issuer/tasks/main.yml
- roles/cluster_issuer/tasks/type/acme/solver/cloudflare.yml
- roles/cluster_issuer/tasks/type/acme/solver/http01.yml
- roles/cluster_issuer/tasks/type/acme/solver/rfc2136.yml
- roles/cluster_issuer/tasks/type/acme/solver/route53.yml
- roles/cluster_issuer/tasks/type/ca/main.yml
- roles/cluster_issuer/tasks/type/self-signed/main.yml
- roles/cluster_issuer/tasks/type/venafi/main.yml
- roles/defaults/defaults/main.yml
- roles/keepalived/tasks/main.yml
- roles/keycloak/tasks/main.yml
- roles/keystone/vars/main.yml
- roles/magnum/vars/main.yml
> [stable/2023.1] Mount CA into Keystone + Magnum

- images/openstack-venv-builder/Dockerfile
> [stable/2023.1] Build requirements from pinned Git hash

- images/openstack-venv-builder/Dockerfile
> [stable/zed] Build requirements from pinned Git hash

- roles/node_feature_discovery/tasks/main.yml
- roles/rabbitmq_cluster_operator/tasks/main.yml
Related-To: https://github.com/vexxhost/atmosphere/issues/1282
Related-To: https://github.com/vexxhost/atmosphere/pull/1308
> Install CRDs for RMQ + NFD

- images/nova/Dockerfile
- images/nova/patches/nova/0000-Reproduce-asym-NUMA-mixed-CPU-policy-bug.patch
- images/nova/patches/nova/0001-Handle-zero-pinned-CPU-in-a-cell-with-mixed-policy.patch
This won't be able to merged to stable/zed for OpenStack/nova and it's already fixed in stable/2023.1, so let's directly put patch to stable/zed.
reference: https://review.opendev.org/c/openstack/nova/+/882531
> [stable/zed] fix: fix CPU zero-pinned issue

- roles/ingress/templates/ingress.yml.j2
fix https://github.com/vexxhost/atmosphere/issues/1278
> fix: fix ingress annotations format

- doc/source/deploy/csi.rst
- roles/defaults/vars/main.yml
- roles/ibm_block_csi_driver/README.md
- roles/ibm_block_csi_driver/defaults/main.yml
- roles/ibm_block_csi_driver/meta/main.yml
- roles/ibm_block_csi_driver/tasks/main.yml
- roles/ibm_block_csi_driver/templates/csi.ibm.com_v1_ibmblockcsi_cr.yaml.j2
- roles/ibm_block_csi_driver/templates/ibm-block-csi-operator.yaml.j2
> Add IBM Block CSI driver

- doc/source/deploy/csi.rst
- roles/defaults/vars/main.yml
- roles/ibm_block_csi_driver/README.md
- roles/ibm_block_csi_driver/defaults/main.yml
- roles/ibm_block_csi_driver/meta/main.yml
- roles/ibm_block_csi_driver/tasks/main.yml
- roles/ibm_block_csi_driver/templates/csi.ibm.com_v1_ibmblockcsi_cr.yaml.j2
- roles/ibm_block_csi_driver/templates/ibm-block-csi-operator.yaml.j2
Signed-off-by: Mohammed Naser mnaser@vexxhost.com
> [stable/2023.1] Add IBM Block CSI driver

- doc/source/deploy/csi.rst
- roles/defaults/vars/main.yml
- roles/ibm_block_csi_driver/README.md
- roles/ibm_block_csi_driver/defaults/main.yml
- roles/ibm_block_csi_driver/meta/main.yml
- roles/ibm_block_csi_driver/tasks/main.yml
- roles/ibm_block_csi_driver/templates/csi.ibm.com_v1_ibmblockcsi_cr.yaml.j2
- roles/ibm_block_csi_driver/templates/ibm-block-csi-operator.yaml.j2
Signed-off-by: Mohammed Naser mnaser@vexxhost.com
> [stable/zed] Add IBM Block CSI driver

- build/pin-images.py
- zuul.d/project.yaml
- **Add pin images for buildset registry**
- **Add missing keepalived dependency**
> Fix collection builds

- zuul.d/playbooks/build-collection/pre.yml
- zuul.d/playbooks/common/configure-buildset-registry.yml
- zuul.d/playbooks/molecule/pre.yml
- zuul.d/project.yaml
> [stable/2023.1] Use buildset registry for collection builds

- build/lint-jobs.py
- roles/barbican/tasks/main.yml
- roles/kube_prometheus_stack/tasks/main.yml
- roles/octavia/tasks/generate_resources.yml
- roles/octavia/tasks/main.yml
- tox.ini
- zuul.d/container-images/cluster-api-provider-openstack.yaml
- zuul.d/container-images/kubernetes-entrypoint.yaml
- zuul.d/container-images/openvswitch.yaml
- zuul.d/container-images/python-openstackclient.yaml
- zuul.d/container-images/ubuntu.yaml
> Improve CI reliability

- build/lint-jobs.py
- roles/barbican/tasks/main.yml
- roles/kube_prometheus_stack/tasks/main.yml
- roles/octavia/tasks/generate_resources.yml
- roles/octavia/tasks/main.yml
- tox.ini
- zuul.d/container-images/cluster-api-provider-openstack.yaml
- zuul.d/container-images/kubernetes-entrypoint.yaml
- zuul.d/container-images/openvswitch.yaml
- zuul.d/container-images/python-openstackclient.yaml
- zuul.d/container-images/ubuntu.yaml
Signed-off-by: Mohammed Naser mnaser@vexxhost.com
> [stable/zed] Improve CI reliability

- doc/source/deploy/csi.rst
- roles/multipathd/handlers/main.yml
- roles/multipathd/tasks/main.yml
- roles/portworx/tasks/main.yml
- roles/portworx/templates/storage_cluster.yml
- **Restart multipathd**
- **Fix portworx token typo**
- **Create namespace ahead of time**
> Add fixes for Portworx

- images/ovn/Dockerfile
- zuul.d/container-images/kubernetes-entrypoint.yaml
- zuul.d/container-images/libvirt-tls-sidecar.yaml
- zuul.d/container-images/libvirtd.yaml
- zuul.d/container-images/magnum.yaml
- zuul.d/container-images/neutron.yaml
- zuul.d/container-images/nova-ssh.yaml
- zuul.d/container-images/nova.yaml
- zuul.d/container-images/openstack-python-runtime.yaml
- zuul.d/container-images/openstack-runtime.yaml
- zuul.d/container-images/openstack-venv-builder.yaml
- zuul.d/container-images/openvswitch.yaml
- zuul.d/container-images/ovn.yaml
- zuul.d/container-images/python-base.yaml
- zuul.d/container-images/ubuntu-cloud-archive.yaml
- zuul.d/container-images/ubuntu.yaml
(cherry picked from commit 1bb945e7d8470d59077851fb9a13b44f64b2e415)
> [stable/zed] feat: build arm64 images for computes

- roles/defaults/vars/main.yml
- roles/kube_prometheus_stack/files/jsonnet/openstack.libsonnet
- roles/openstack_exporter/tasks/main.yml
(cherry picked from commit 08ff881f0191ab23979009c5243463ed6a379fa6)
(cherry picked from commit 02650c9ded39d40b465eb029cc14f87bb2c180ab)
> [stable/zed] Add build request failure monitoring [ATMOSPHERE-249]

- roles/defaults/vars/main.yml
- roles/kube_prometheus_stack/files/jsonnet/openstack.libsonnet
- roles/openstack_exporter/tasks/main.yml
(cherry picked from commit 08ff881f0191ab23979009c5243463ed6a379fa6)
> [stable/2023.1] Add build request failure monitoring [ATMOSPHERE-249]

- roles/ingress/templates/ingress.yml.j2
fix https://github.com/vexxhost/atmosphere/issues/1278\n\nCloses #1357
> [stable/2023.1] fix: fix ingress annotations format

- roles/ingress/templates/ingress.yml.j2
fix https://github.com/vexxhost/atmosphere/issues/1278\n\nCloses #1358
> [stable/zed] fix: fix ingress annotations format

- doc/source/deploy/csi.rst
- roles/csi/meta/main.yml
- roles/multipathd/handlers/main.yml
- roles/multipathd/tasks/main.yml
- roles/multipathd/templates/multipath.conf.j2
- roles/portworx/defaults/main.yml
- roles/portworx/meta/main.yml
- roles/portworx/tasks/main.yml
- roles/portworx/templates/config.yml
- roles/portworx/templates/portworx.yml
- roles/portworx/templates/storage_class.yml
- roles/portworx/templates/storage_cluster.yml
- roles/powerstore_csi/tasks/main.yml
> [stable/zed] Add Portworx CSI support

- .charts.yml
- charts/openvswitch/Chart.yaml
- charts/openvswitch/templates/daemonset.yaml
- charts/openvswitch/values.yaml
- images/openvswitch/Dockerfile
- **Add tini to Open vSwitch**
- **Bump Open vSwitch chart to support Tini**
> Start using Tini for Open vSwitch

- doc/source/deploy/csi.rst
- roles/multipathd/handlers/main.yml
- roles/multipathd/tasks/main.yml
- roles/portworx/tasks/main.yml
- roles/portworx/templates/storage_cluster.yml
- **Restart multipathd**
- **Fix portworx token typo**
- **Create namespace ahead of time**\n\nCloses #1435
> [stable/zed] Add fixes for Portworx

- roles/multipathd/defaults/main.yml
- roles/multipathd/tasks/main.yml
> [stable/zed] fix: make multipathd repository overridable for offline install

- images/neutron/Dockerfile
relate to https://github.com/vexxhost/atmosphere/pull/1458/files
> [stable/2024.1] chore: use git ref for neutron-vpnaas

- images/neutron/Dockerfile
relate to https://github.com/vexxhost/atmosphere/pull/1458
> [stable/2023.2] chore: use git ref for neutron-vpnaas

- .charts.yml
- charts/openvswitch/Chart.yaml
- charts/openvswitch/templates/daemonset.yaml
- charts/openvswitch/values.yaml
- images/openvswitch/Dockerfile
Add tini to Open vSwitch
Bump Open vSwitch chart to support Tini
> [stable/zed] Start using Tini for Open vSwitch

- charts/neutron/templates/bin/_neutron-policy-server.sh.tpl
- charts/neutron/templates/configmap-bin.yaml
- charts/neutron/templates/configmap-etc.yaml
- charts/neutron/templates/deployment-server.yaml
- charts/neutron/templates/service-server.yaml
- charts/neutron/values.yaml
- charts/patches/neutron/0002-add-neutron-policy-server.patch
- images/neutron/Dockerfile
- roles/defaults/vars/main.yml
- roles/neutron/defaults/main.yml
- roles/neutron/tasks/main.yml
- roles/neutron/vars/main.yml
Depends-On https://github.com/vexxhost/neutron-policy-server/pull/1\n\nCloses #1482
> [stable/2024.1] feat: add neutron_policy_server support

- charts/neutron/templates/bin/_neutron-policy-server.sh.tpl
- charts/neutron/templates/configmap-bin.yaml
- charts/neutron/templates/configmap-etc.yaml
- charts/neutron/templates/deployment-server.yaml
- charts/neutron/templates/service-server.yaml
- charts/neutron/values.yaml
- charts/patches/neutron/0002-add-neutron-policy-server.patch
- images/neutron/Dockerfile
- roles/defaults/vars/main.yml
- roles/neutron/defaults/main.yml
- roles/neutron/tasks/main.yml
- roles/neutron/vars/main.yml
Depends-On vexxhost/neutron-policy-server#1
> [stable/2023.1] feat: add neutron_policy_server support

- charts/neutron/templates/bin/_neutron-policy-server.sh.tpl
- charts/neutron/templates/configmap-bin.yaml
- charts/neutron/templates/configmap-etc.yaml
- charts/neutron/templates/deployment-server.yaml
- charts/neutron/templates/service-server.yaml
- charts/neutron/values.yaml
- charts/patches/neutron/0002-add-neutron-policy-server.patch
- images/neutron/Dockerfile
- roles/defaults/vars/main.yml
- roles/neutron/defaults/main.yml
- roles/neutron/tasks/main.yml
- roles/neutron/vars/main.yml
Depends-On vexxhost/neutron-policy-server#1
> [stable/zed] feat: add neutron_policy_server support

- roles/nova/vars/main.yml
Fixes CLOUDOPS-233-live-migration-broken-on-2023-1
> Fix issue Live migration broken on 2023.1

- roles/kube_prometheus_stack/files/jsonnet/mixins.libsonnet
Appends new CephHealthDetail* alerts and disables redundant alerts from ceph-mixin.
> ceph: Add CephHealthDetail alerts

- doc/source/admin/integration.rst
> chore: add docs for neutron policy server

- images/neutron/Dockerfile
relate to https://github.com/vexxhost/atmosphere/pull/1458
> [stable/zed] chore: use git ref for neutron-vpnaas

- roles/keycloak/vars/main.yml
- roles/kube_prometheus_stack/vars/main.yml
> Add support to collect keycloak application metrics to prometheus

- charts/ovn/templates/bin/_ovn-network-logging-parser.sh.tpl
- charts/ovn/templates/configmap-bin.yaml
- charts/ovn/templates/configmap-etc.yaml
- charts/ovn/templates/daemonset-controller-gw.yaml
- charts/ovn/templates/secret-vector.yaml
- charts/ovn/values.yaml
- charts/patches/ovn/0002-add-logging-parser.patch
- images/neutron/Dockerfile
- roles/defaults/vars/main.yml
- roles/neutron/vars/main.yml
- roles/ovn/defaults/main.yml
- roles/ovn/vars/main.yml
depends-on: #1541
fix https://github.com/vexxhost/atmosphere/issues/1559
> [stable/zed] feat: add ovn_network_logging_parser support

- charts/ovn/templates/bin/_ovn-network-logging-parser.sh.tpl
- charts/ovn/templates/configmap-bin.yaml
- charts/ovn/templates/configmap-etc.yaml
- charts/ovn/templates/daemonset-controller-gw.yaml
- charts/ovn/templates/secret-vector.yaml
- charts/ovn/values.yaml
- charts/patches/ovn/0002-add-logging-parser.patch
- images/neutron/Dockerfile
- roles/defaults/vars/main.yml
- roles/neutron/vars/main.yml
- roles/ovn/defaults/main.yml
- roles/ovn/vars/main.yml
depends-on: #1541
fix https://github.com/vexxhost/atmosphere/issues/1557
> [stable/2023.1] feat: add ovn_network_logging_parser support

- playbooks/csi.yml
The multipathd role needs to gather facts.
> Gather facts for CSI

- images/nova/Dockerfile
- roles/nova/vars/main.yml
> [stable/2023.2] feat: add nova failure domain filters

- doc/source/deploy/certificates.rst
Closes https://github.com/vexxhost/atmosphere/issues/1612
And Godaddy's "feature"
> feat: add cloudflare docs and note for godaddy

- images/nova/Dockerfile
- roles/nova/vars/main.yml
> [stable/2023.1] feat: add nova failure domain filters

- .charts.yml
- charts/goldpinger/.helmignore
- charts/goldpinger/Chart.yaml
- charts/goldpinger/templates/_helpers.tpl
- charts/goldpinger/templates/clusterrole.yaml
- charts/goldpinger/templates/clusterrolebinding.yaml
- charts/goldpinger/templates/configmap.yaml
- charts/goldpinger/templates/daemonset.yaml
- charts/goldpinger/templates/ingress.yaml
- charts/goldpinger/templates/prometheusrule.yaml
- charts/goldpinger/templates/role.yaml
- charts/goldpinger/templates/rolebinding.yaml
- charts/goldpinger/templates/service.yaml
- charts/goldpinger/templates/serviceaccount.yaml
- charts/goldpinger/templates/servicemonitor.yaml
- charts/goldpinger/values.yaml
- playbooks/monitoring.yml
- roles/defaults/vars/main.yml
- roles/goldpinger/README.md
- roles/goldpinger/defaults/main.yml
- roles/goldpinger/meta/main.yml
- roles/goldpinger/tasks/main.yml
- roles/goldpinger/vars/main.yml
- roles/kube_prometheus_stack/files/dashboards/goldpinger.json
- roles/kube_prometheus_stack/files/dashboards/node-exporter-full.json
- roles/kube_prometheus_stack/files/jsonnet/openstack.libsonnet
- roles/kube_prometheus_stack/tasks/main.yml
- roles/kube_prometheus_stack/templates/configmap-dashboard.yaml.j2
- roles/kube_prometheus_stack/vars/main.yml
- tox.ini
> Add Goldpinger + node-exporter-full

- roles/kube_prometheus_stack/vars/main.yml
> Change promethues to use pvc for data store

- images/horizon/Dockerfile
- images/horizon/patches/horizon/0000-normalize-url-join-for-placement.patch
upstream patch: https://review.opendev.org/c/openstack/horizon/+/924729
fix https://github.com/vexxhost/atmosphere/issues/1678
> [stable/2024.1] fix(horizon): apply a patch to fix resource provider panel

- .gitignore
- roles/horizon/vars/main.yml
Related: https://github.com/vexxhost/atmosphere/pull/1284/files
> horizon: Disable backups panel if cinder-backup is disabled

- doc/source/deploy/certificates.rst
- roles/defaults/defaults/main.yml
- roles/ingress/defaults/main.yml
- roles/ingress/templates/ingress.yml.j2
- roles/keycloak/defaults/main.yml
- roles/keycloak/tasks/main.yml
- roles/kube_prometheus_stack/defaults/main.yml
- roles/kube_prometheus_stack/vars/main.yml
> [ATMOSPHERE-302] fix: set variables for cluster issuer name for keycloak and kube-prom-stack

- playbooks/openstack.yml
> [ATMOSPHERE-321] Fix run multipathd role failure

- charts/libvirt/templates/daemonset-libvirt.yaml
> [ATMOSPHERE-21] Support libvirt.nova metadata in metrics for libvirt exporter

- images/python-openstackclient/Dockerfile
> [ATMOSPHERE-328] images(python-openstackclient): Add python-ironicclient

- images/python-openstackclient/Dockerfile
> [ATMOSPHERE-330] images(python-openstackclient): Add python-ironicclient

- roles/kube_prometheus_stack/vars/main.yml
> [ATMOSPHERE-340] Support collect softirq for node-exporter

- roles/kube_prometheus_stack/vars/main.yml
> [ATMOSPHERE-343] Support collect softirq for node-exporter

- charts/libvirt/templates/daemonset-libvirt.yaml
> [ATMOSPHERE-337] 2024 1 caracal libvirt exporter not having libvirt nova setting enabled

- roles/kube_prometheus_stack/vars/main.yml
> [ATMOSPHERE-344] 2024 1 caracal enable softirq monitoring

- roles/kube_prometheus_stack/vars/main.yml
> [ATMOSPHERE-342] zed enable softirq monitoring

- roles/openvswitch/tasks/main.yml
Depends-On: https://github.com/vexxhost/atmosphere/pull/1752
> [ATMOSPHERE-379] Add openvswitch image pull for caching before upgrade

- roles/nova/vars/main.yml
Depends-On: https://github.com/vexxhost/atmosphere/pull/1766
> [ATMOSPHERE-377] Enable Nova automatic host discovery at a set interval

- roles/barbican/vars/main.yml
- roles/cinder/vars/main.yml
- roles/designate/vars/main.yml
- roles/glance/vars/main.yml
- roles/heat/vars/main.yml
- roles/keystone/vars/main.yml
- roles/magnum/vars/main.yml
- roles/manila/vars/main.yml
- roles/neutron/vars/main.yml
- roles/nova/vars/main.yml
- roles/octavia/vars/main.yml
- roles/placement/vars/main.yml
- roles/staffeln/vars/main.yml
Depends-On: https://github.com/vexxhost/chart-vendor/pull/2
Depends-On: https://github.com/vexxhost/atmosphere/pull/1752
> Tune database values

- roles/openvswitch/tasks/main.yml
Depends-On: https://github.com/vexxhost/atmosphere/pull/1766
> [ATMOSPHERE-383] Add openvswitch image pull for caching before upgrade

- roles/defaults/vars/main.yml
- roles/kube_prometheus_stack/defaults/main.yml
- roles/kube_prometheus_stack/tasks/main.yml
- roles/kube_prometheus_stack/vars/main.yml
> [stable/2023.1] Add TLS to node exporter

- playbooks/openstack.yml
> [ATMOSPHERE-322] Fix run multipathd role failure (#1716)

- playbooks/openstack.yml
> [ATMOSPHERE-323] Fix run multipathd role failure (#1716)

- playbooks/openstack.yml
(cherry picked from commit d31cea5be7328ec981f1cad00014cc3554b706d4)
> [ATMOSPHERE-325] Fix run multipathd role failure (#1716)

- playbooks/openstack.yml
> [ATMOSPHERE-324] Fix run multipathd role failure (#1716)

- .charts.yml
- charts/cinder/Chart.yaml
- charts/cinder/templates/bin/_bootstrap.sh.tpl
- charts/cinder/templates/deployment-api.yaml
- charts/cinder/templates/deployment-backup.yaml
- charts/cinder/templates/deployment-scheduler.yaml
- charts/cinder/templates/deployment-volume.yaml
- charts/cinder/templates/secret-db.yaml
- charts/cinder/templates/secret-external-ceph-keyring.yaml
- charts/cinder/templates/secret-keystone.yaml
- charts/cinder/templates/secret-rabbitmq.yaml
- charts/cinder/values.yaml
Ref: https://review.opendev.org/c/openstack/openstack-helm/+/926699
relate to https://github.com/vexxhost/atmosphere/issues/1804
> [CLOUDOPS-344] fix: bump cinder chart and add bootstrap fix

- roles/kube_prometheus_stack/files/dashboards/goldpinger.json
Remove threshold for nodes in grafana dashboard which may cause end user confuseing
> [ATMOSPHERE-428] Fix goldpinger grafana dashboard threshold for nodes

- roles/keycloak/tasks/main.yml
- roles/percona_xtradb_cluster/vars/main.yml
fix https://github.com/vexxhost/atmosphere/issues/1838
> fix: use master pxc_strict_mode

- roles/ironic/vars/main.yml
See https://review.opendev.org/c/openstack/ironic/+/907148
> [PS-274] Set rbac_service_role_elevated_access to true

- playbooks/kubernetes.yml
- roles/defaults/vars/main.yml
fixes https://github.com/vexxhost/atmosphere/issues/1256
> fix: add kube_vip image

- images/ironic/Dockerfile
https://bugs.launchpad.net/ironic/+bug/2071740
> [ATMOSPHERE-445] Ironic Unvalidated image data passed to qemu-img (CVE-2024-44082)

- images/magnum/Dockerfile
- images/magnum/patches/magnum/0000-Revert-Remove-use-of-autocommit.patch
See: https://bugs.launchpad.net/magnum/+bug/2067345
> Database connectivity workaround for Magnum

- images/glance/Dockerfile
port upstream commit https://github.com/openstack/glance/commits/unmaintained/zed/
> [stable/zed] OSSA-2024-001 (glance) (#1582)

- roles/loki/vars/main.yml
fix #490
Reviewed-by: Oleksandr K.
> [ATMOSPHERE-438] chore: Add loki rule to delect Nova cell down

- roles/loki/vars/main.yml
fix #490
Reviewed-by: Oleksandr K.
> [ATMOSPHERE-440] chore: Add loki rule to delect Nova cell down

- roles/loki/vars/main.yml
fix #490
Reviewed-by: Oleksandr K.
> [ATMOSPHERE-439] chore: Add loki rule to delect Nova cell down

- roles/percona_xtradb_cluster/tasks/main.yml
Depends-On: https://github.com/vexxhost/atmosphere/pull/2010
> fix: increate timeout waiting for pxc creation

- .charts.yml
- charts/ovn/templates/daemonset-controller-gw.yaml
- charts/ovn/templates/daemonset-controller.yaml
- charts/patches/ovn/0000-upstream-893739.patch
- charts/patches/ovn/0001-switch-to-ovn-kubernetes.patch
- charts/patches/ovn/0002-add-logging-parser.patch
this error has been revealed by https://github.com/vexxhost/atmosphere/pull/1983 Good to have this go unit test in CI soon
Moved to local patch https://review.opendev.org/c/openstack/openstack-helm-infra/+/893739/10
> fix: sync ovn chart upstream patch

- roles/kube_prometheus_stack/files/jsonnet/mixins.libsonnet
Depends-On: https://github.com/vexxhost/atmosphere/pull/2023
> [ATMOSPHERE-508] Disable CephPGImbalance

- roles/keycloak/tasks/main.yml
- roles/keycloak/vars/main.yml
fixes: https://github.com/vexxhost/atmosphere/issues/1839
> fix: add ingress annotations for keycloak

- images/cinder/patches/cinder/0002-Directly-import-converted-image-to-RBD.patch
ref: https://review.opendev.org/c/openstack/cinder/+/933006
> [ATMOSPHERE-479] fix: Directly import converted image to RBD

- images/nova/Dockerfile
- roles/nova/vars/main.yml
update the nova image include emulated-tpm packages 
update the nova compute conf to enable emulated-tpm
> [CLOUDOPS-563]  Enable Emulated-TPM

- roles/designate/vars/main.yml
- roles/manila/vars/main.yml
- roles/nova/vars/main.yml
- designate
- manila
- nova
Depends-on: https://github.com/vexxhost/atmosphere/pull/2087
> [ATMOSPHERE-553] Disable log config append

- charts/barbican/templates/bin/_simple_crypto_kek_rewrap.py.tpl
- charts/patches/barbican/0002-Use-more-standard-configs-for-DBs.patch
Ref from #2263
Also push to  https://review.opendev.org/c/openstack/openstack-helm/+/938638
> fix: remove autocommit from barbican charts

- images/cinder/Dockerfile
- images/cinder/patches/cinder/0002-Directly-import-converted-image-to-RBD.patch
relate to https://github.com/vexxhost/atmosphere/pull/2298
> [stable/2023.1][CLOUDOPS-748] fix fileutils missing

- roles/kube_prometheus_stack/files/dashboards/haproxy.json
- roles/kube_prometheus_stack/tasks/main.yml
- roles/kube_prometheus_stack/vars/main.yml
- roles/percona_xtradb_cluster/tasks/main.yml
https://grafana.com/grafana/dashboards/12693-haproxy-2-full/
Fixes #2388
> support scrape percona haproxy metrics

- .charts.yml
- .github/styles/config/vocabularies/Base/accept.txt
- .vale.ini
- charts/octavia/templates/bin/_db-sync.sh.tpl
- charts/octavia/templates/configmap-etc.yaml
- charts/octavia/templates/job-db-drop.yaml
- charts/octavia/templates/job-db-init.yaml
- charts/octavia/templates/secret-db-persistence.yaml
- charts/octavia/values.yaml
- images/octavia/Dockerfile
- images/octavia/patches/octavia/0001-jobboard-Support-authentication-and-SSL-for-Redis-Se.patch
- releasenotes/notes/add-amphere-v2-df19890ea67e2486.yaml
- releasenotes/notes/backport-octavia-redis-fixes-551c9f3f145e3de6.yaml
- roles/octavia/defaults/main.yml
- roles/octavia/vars/main.yml
- roles/openstack_helm_endpoints/vars/main.yml
Related: ATMOSPHERE-544
Change-Id: I4d50fe0bb805f08f2ec1df2061cb0467721e7de0 (cherry picked from commit 566e154dd0915779712c80d30041a9082b463e03)
> [ATMOSPHERE-544] Add Octavia Amphere v2 support

- images/barbican/Dockerfile
- images/cinder/Dockerfile
- images/designate/Dockerfile
- images/glance/Dockerfile
- images/heat/Dockerfile
- images/horizon/Dockerfile
- images/ironic/Dockerfile
- images/keystone/Dockerfile
- images/magnum/Dockerfile
- images/manila/Dockerfile
- images/neutron/Dockerfile
- images/nova/Dockerfile
- images/octavia/Dockerfile
- images/openstack-venv-builder/Dockerfile
- images/ovn-bgp-agent/Dockerfile
- images/ovn-bgp-agent/patches/ovn-bgp-agent/0001-Implement-driver-concept-for-BGP-agent.patch
- images/ovn-bgp-agent/patches/ovn-bgp-agent/0002-Add-the-support-of-create-kubernetes-resource.patch
- images/placement/Dockerfile
Change-Id: I6b6df2421e36429797409de5f566e75b6a6e5e14
> chore(deps): update openstack (main) and Update ovn-bgp-agent patches

- images/octavia/patches/octavia/0002-redis-Support-multiple-sentinel-servers.patch
- releasenotes/notes/backport-octavia-redis-fixes-551c9f3f145e3de6.yaml
Change-Id: Ia233cf5f9b19df7443f6acb2bf785f684c3a5bc4
> [stable/2023.2]Backport redis multiple sentinel support

- .github/styles/config/vocabularies/Base/accept.txt
- releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml
- roles/percona_xtradb_cluster/vars/main.yml
- roles/percona_xtradb_cluster/vars_test.go
Backport from https://github.com/vexxhost/atmosphere/pull/2546
Change-Id: Ibb2a18d1e3744b22abbd61f86b7d4a43cfa790c8
> [stable/zed] Drop max_allowed_packet config

- charts/openvswitch/templates/bin/_openvswitch-vswitchd.sh.tpl
- charts/patches/openvswitch/0002-clean-ovs-pid.patch
- charts/patches/openvswitch/releasenotes/notes/fix-stale-ovs-pid-file-d8eee12d13ad0ffe.yaml
> fix(ovs): Remove stale PID file at OVS startup

- .github/styles/config/vocabularies/Base/accept.txt
- molecule/aio/prepare.yml
- playbooks/csi.yml
- playbooks/openstack.yml
- releasenotes/notes/enable-auth-token-cache-in-rook-9e15863e87fbe4ba.yaml
- roles/rook_ceph_cluster/vars/main.yml
(cherry picked from commit 31544c7ac36b9724302f8e8b3fe2f9cb86c3610c)
> feat: enable auth token cache in rook (#2653)

- .github/styles/config/vocabularies/Base/accept.txt
- .pre-commit-config.yaml
- docker-bake.hcl
- images/cluster-api-provider-openstack/Dockerfile
- images/source-patch/Dockerfile
- patches/kubernetes-sigs/cluster-api-provider-openstack/allow-switching-filter-name-to-id.patch
- releasenotes/notes/fix-capi-filter-name-to-id-b0039109a1056c06.yaml
- roles/defaults/vars/main.yml
(cherry picked from commit 7e700e6308bbd794e51dda5a75bf299bf36a522c)
> [Backport stable/2023.1] ✨ feat: add support for switching OpenStackCluster filter to ID transition

- .github/styles/config/vocabularies/Base/accept.txt
- .pre-commit-config.yaml
- docker-bake.hcl
- images/cluster-api-provider-openstack/Dockerfile
- images/source-patch/Dockerfile
- patches/kubernetes-sigs/cluster-api-provider-openstack/allow-switching-filter-name-to-id.patch
- releasenotes/notes/fix-capi-filter-name-to-id-b0039109a1056c06.yaml
- roles/defaults/vars/main.yml
…ition (#2681)
(cherry picked from commit 7e700e6308bbd794e51dda5a75bf299bf36a522c)
>  [Backport stable/zed] ✨ feat: add support for switching OpenStackCluster filter to ID transition

- images/barbican/Dockerfile
- images/cinder/Dockerfile
- images/designate/Dockerfile
- images/glance/Dockerfile
- images/heat/Dockerfile
- images/horizon/Dockerfile
- images/horizon/patches/magnum-ui/0001-fix-disable-resizing-for-admins.patch
- images/horizon/patches/magnum-ui/0002-capi-Avoid-going-through-Heat-for-worker-list.patch
- images/ironic/Dockerfile
- images/keystone/Dockerfile
- images/magnum/Dockerfile
- images/manila/Dockerfile
- images/neutron/Dockerfile
- images/nova/Dockerfile
- images/octavia/Dockerfile
- images/openstack-venv-builder/Dockerfile
- images/placement/Dockerfile
- images/tempest/Dockerfile
> 🔧 fix: update Dockerfiles to use 2023.2-eol branch for dependencies

- .github/styles/config/vocabularies/Base/accept.txt
- images/neutron/Dockerfile
- releasenotes/notes/add-neutron-modules-dragent-and-genericswitch-183cc6474c376c12.yaml
For Baremetal switching we need `networking-generic-switch`
For bgp-dragent we need `neutron-dynamic-routing`
> feat: add dynamic-routing and networking-generic-switch support for Neutron

- releasenotes/notes/Fix-cinder-auth-type-9ea017879a578f2a.yaml
- roles/nova/vars/main.yml
[stable/2024.1]add missing cinder.auth_type
Change-Id: Idfa71708a45c1a3db9115601ba580432883cbbec
> [stable/2024.1]add missing cinder.auth_type

- images/openstack-venv-builder/Dockerfile
> ✨ chore: clean uv cache before creating virtual environment

- .github/styles/config/vocabularies/Base/accept.txt
- images/magnum/Dockerfile
- releasenotes/notes/fix-magnum-trusts-ee4824c8e6e3610d.yaml
Change-Id: I03fbb50fb95f753987015651bbd32c496a920ab7
> [stable/2024.2] fix magnum trusts

- images/cinder/patches/cinder/0002-Directly-import-converted-image-to-RBD.patch
commit c579760dda in cinder break some import in cinder image.
Change-Id: I44e25e95c2e982e2452e21bb2559bde1b41dd48d
> [cinder] sync image patch with RBD

- .github/styles/config/vocabularies/Base/accept.txt
- images/magnum/Dockerfile
- releasenotes/notes/fix-magnum-trusts-ee4824c8e6e3610d.yaml
ref https://review.opendev.org/c/openstack/magnum/+/954555
> [stable/2024.1] fix magnum trusts

- releasenotes/notes/tune-down-producer-a12e366b19f5b839.yaml
- roles/designate/vars/main.yml
Related: https://github.com/vexxhost/atmosphere/issues/2824
> fix(designate): set producer replicas to 1

- build/build-manila-image.sh
- docker-bake.hcl
- images/barbican/Dockerfile
- images/cinder/Dockerfile
- images/designate/Dockerfile
- images/glance/Dockerfile
- images/heat/Dockerfile
- images/horizon/Dockerfile
- images/ironic/Dockerfile
- images/keystone/Dockerfile
- images/magnum/Dockerfile
- images/manila/Dockerfile
- images/neutron/Dockerfile
- images/nova/Dockerfile
- images/octavia/Dockerfile
- images/openstack-venv-builder/Dockerfile
- images/ovn-bgp-agent/Dockerfile
- images/placement/Dockerfile
- images/tempest/Dockerfile
- renovate.json
> chore: use github.com for git clones

- .github/styles/config/vocabularies/Base/accept.txt
- releasenotes/notes/fix-staffeln-policy-flag-f890d2115be282bf.yaml
- roles/cinder/tasks/main.yml
Change-Id: I2d47ba3110a55207508d7f917122fb4de76c3a39
> Fix cinder staffeln conf reference

- charts/neutron/templates/bin/_neutron-server.sh.tpl
- charts/patches/neutron/0008-Neutron-ovn-adopt-uwsgi.patch
fix extra neutron config files aren't loaded using uwsgi start script for openvswitch network backend
> [stable/2025.1]fix: update neutron chart to fix openvswitch config missing

- roles/senlin/vars/main.yml
Change-Id: I9d477e130b943fd2bdd6954aaf895aedf9d41631
(cherry picked from commit e35af2dbb539d591b34785203ef04815daf23b49)
> [stable/zed]Fix senlin upgrade zed

- .github/styles/config/vocabularies/Base/accept.txt
- images/neutron/Dockerfile
- releasenotes/notes/neutron-policy-server-network-scope-32cc55500d68fac9.yaml
bump to a215317bfa147f29dd4e85ff96a54982384c8ba1
Change-Id: I56210cc52f0cb7a2bd64b3fea056fa8b972b77fe
> Bump neutron-policy-server

- .github/styles/config/vocabularies/Base/accept.txt
- charts/neutron/templates/bin/_neutron-server.sh.tpl
- charts/neutron/templates/deployment-server.yaml
- charts/patches/neutron/0008-Fix-Add-Missing-Neutron-OVN-VPN-Configuration.patch
- releasenotes/notes/fix-ovn-vpn-on-neutron-server-ee091b48195b945d.yaml
- roles/neutron/vars/main.yml
(cherry picked from commit 34fd0152e0582ca6f4e4f9f127b7314f45f50831)
Change-Id: Ie063ee8a610076503d996c8957273a00363f097d
(cherry picked from commit 5587d0609d37ffe7cfa6a6fdaf24ee9a97e30a10)
> [Backport stable/2024.1] Fix: Add Missing Neutron OVN VPN Configuration

- .github/styles/config/vocabularies/Base/accept.txt
- releasenotes/notes/octavia-valkey-cert-fix-abf25ad08313e162.yaml
- roles/octavia/vars/main.yml
Change-Id: Ia6b47142e362449907469691b9151d24ed6e6f9a
> Fix Octavia LB cert renew
