roles/openstack_helm_glance/defaults/main.yml
This should take care of using an image that has the missing `kubectl` package as well as the Cinder ones.
Fixes #36
=> Add missing packages to Glance

roles/openstack_helm_cinder/vars/main.yml
Adopt config image_conversion_disable from [1].
Set it to true by default.
[1] https://review.opendev.org/c/openstack/cinder/+/839793
=> Set image_conversion_disable to true by default

roles/openstack_helm_nova/vars/main.yml
Change noVNC to use novnc_lite.html instead of vnc_auto.html.
vnc_auto.html was replaced in noVNC long time ago, we should adopt that change as well.
ref: https://github.com/novnc/noVNC/issues/695
=> Switch to use vnc_lite instead of vnc_auto

roles/openstack_helm_ingress/tasks/main.yml
Default is set to openstack (matching current configuration)
=> feat: allow for a custom ingressClassName on OpenStack component ingress objects

roles/coredns/tasks/main.yml, roles/openstack_helm_neutron/vars/main.yml
Default is set to '10.96.0.20' (matching current configuration). This will support Atmosphere running the 'openstack' playbook against a Kubernetes cluster that is not using the default `10.96.0.0/12` implemented with `kubeadm`.
=> feat: allow for a custom cluster IP address for the neutron coredns service

roles/cilium/tasks/main.yml
Make clusterPoolIPv4PodCIDR configurable, this to solve conflicts with the 10.0.0.0 subnets
=> Make clusterPoolIPv4PodCIDR configurable

roles/openstack_helm_ingress/tasks/main.yml, roles/openstack_helm_ingress/vars/main.yml
Defaults for `cert-manager.io/cluster-issuer` remains `atmosphere` and for `secretName` remains `{{ openstack_helm_ingress_service_name }}-certs`.
This allows for those defaults to be overridden by setting the `openstack_helm_ingress_secretname` and `openstack_helm_ingress_clusterissuer` variables in the cluster inventory.
=> feat: allow for custom clusterissuer and certificate secretName when atmosphere is not responsible for cert-manager

molecule/default/destroy.yml
Correct task "Upload logs to object storage"
When the GITHUB_RUN_ID & GITHUB_RUN_NUMBER variable is undefined they return  a "" string.
=> fix: Correct task "Upload logs to object storage"

atmosphere/operator/api/types.py, atmosphere/operator/tasks.py, atmosphere/tasks/kubernetes/flux.py, atmosphere/tests/unit/operator/test_objects.py, atmosphere/tests/unit/operator/test_types.py, roles/openstack_helm_octavia/tasks/main.yml, roles/openstack_helm_octavia/vars/main.yml
This PR includes following changes;
- Set retries as 3 for helmreleases managed by atmosphere operator (relates to https://github.com/vexxhost/atmosphere/issues/240)
- Fix idempotent failure in openstack_helm_octavia role by adding unique and sort filter for `_openstack_helm_octavia_controller_ip_port_list` variable
=> feat: Set retries of helmreleases

roles/openstack_cli/defaults/main.yml
The Magnum CLI client is missing.
=> Feat: Install Magnum client

roles/upload_helm_chart/tasks/main.yml
Instead of using times for comparing, use checksum. It will fix idempotence issue
=> fix: Synchronize files based on checksum in upload_helm_chart role

roles/openstack_helm_tempest/meta/main.yml, roles/openstack_helm_tempest/tasks/main.yml
https://github.com/vexxhost/atmosphere/actions/runs/4012750185/jobs/6891450314
molecule verify step failed because tempest role was setting resource ids in wrong variable
=> fix: Fix tempest helm values var name

.github/workflows/lint.yml, .github/workflows/test.yml
GH doesn't provide cancellation per action, but per workflow.
It will ease cancellation of molecule test.
=> chore: Move pre-commit action to lint workflow

internal/pkg/image_repositories/build_workflow.go
oslo.cache requires bmemcached for oslo_cache.memcache_pool backend type from Zed https://github.com/openstack/oslo.cache/commit/7c6effd10e7c09f75fe0c644dab418ada4dc5e8a
=> fix: Add bmemcached

roles/kubernetes/defaults/main.yml, roles/kubernetes/tasks/main.yml, roles/kubernetes/templates/crictl.yaml.j2, roles/kubernetes/templates/kubeadm.yaml.j2
Without configuration crictl complains about deprecation:
```
WARN[0000] image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.
ERRO[0000] unable to determine image API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/dockershim.sock: connect: no such file or directory
```
=> feat: add crictl.yaml config

roles/kubernetes/files/noswap.service, roles/kubernetes/handlers/main.yml, roles/kubernetes/tasks/main.yml
Current bootstrap configuration for swap does not survive after node reboot. This change introduces new `systemd` service which runs `swapoff` before `kubelet` start.
=> feat: always disable swap on node startup

roles/percona_xtradb_cluster/README.md
With the 8.0 image you can create backups, but you can not restore the backups.
Atmosphere uses Percona 5.7. With a 8.0 backup you can not restore to a 5.7 Percona cluster.
=> Update percona backup image

roles/horizon/vars/main.yml
OpenStack Helm enables the Horizon service to be embedded in an iframe
by default. This is a security risk and should be disabled.
This patch disables the embedding of Horizon in an iframe.
=> fix: disallow embedded of horizon in iframe

roles/magnum/tasks/main.yml
To include https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1493
=> chore: Update capo version to 0.7.1

roles/defaults/defaults/main.yml, roles/magnum/defaults/main.yml, roles/magnum/tasks/main.yml
We decied to maintain our own forked version of CAPO https://github.com/vexxhost/cluster-api-provider-openstack. Ofc, this will be synced with upstream.
This PR overrides the default CAPO in cluster-api deployment.
https://github.com/vexxhost/cluster-api-provider-openstack/releases/tag/v0.7.1-1
=> feat: override CAPO

molecule/default/create.yml, molecule/default/heat/server.yaml, molecule/default/heat/stack.yaml
Use environment variable `ATMOSPHERE_CREATE_BASTION_HOST` to create another host that attach direct to public network and to floating ip so it can play an bastion host for environment build by molecule
=> Add bastion host to molecule build env

galaxy.yml, internal/pkg/image_repositories/build_workflow.go, internal/pkg/image_repositories/template/Dockerfile, playbooks/kubernetes.yml, roles/defaults/defaults/main.yml
To remove flux dependency from magnum cluster-api driver, we are gonna use helm to install cluster autoscaler and it requires helm cli.
=> feat: enable autoscaler for magnum

roles/kube_prometheus_stack/files/jsonnet/legacy.libsonnet
This alrert will check if node using non LTS kernel. We added this alert as non LTS kernel could be problematic like in https://github.com/vexxhost/atmosphere/issues/401
Related: https://github.com/vexxhost/atmosphere/issues/402
=> Add NodeNonLTSKernel alert

roles/magnum/tasks/main.yml, roles/vsphere_csi/README.md, roles/vsphere_csi/meta/main.yml, roles/vsphere_csi/tasks/main.yml
fix: https://github.com/vexxhost/atmosphere/issues/400
Some users have been facing authorization issues because the old RBAC resources were keeping in the cluster after https://github.com/vexxhost/atmosphere/commit/158823643ded6811eba712e293c104d798b7e599 change applied.
This PR will remove the old RBAC resources which breaks the auth.
=> fix: Remove old mcapi RBAC resources

roles/barbican/vars/main.yml, roles/cinder/vars/main.yml, roles/designate/vars/main.yml, roles/glance/vars/main.yml, roles/heat/vars/main.yml, roles/magnum/vars/main.yml, roles/manila/vars/main.yml, roles/neutron/vars/main.yml, roles/nova/vars/main.yml, roles/octavia/vars/main.yml, roles/placement/vars/main.yml, roles/senlin/vars/main.yml
If application credentials with access rules are required, an OpenStack service using keystonemiddleware to authenticate with keystone, needs to define service_type in its configuration file.
Once https://review.opendev.org/c/openstack/openstack-helm/+/883066 is merged, we can revert this PR.
fix: https://github.com/vexxhost/atmosphere/issues/409
=> fix(auth): Define service_type in keystone_authtoken

roles/nova/vars/main.yml
This avoid nova-barbican communication go cross ingress
fix https://github.com/vexxhost/atmosphere/issues/428
=> fix(nova): Set barbican_endpoint_type as internal

roles/manila/vars/main.yml
This patch switch to use security group name for
`service_instance_security_group` instead of id.
fix https://github.com/vexxhost/atmosphere/issues/393
=> fix(manila): use sg name for manila

roles/manila/vars/main.yml
As the name for security group manila-service-security-group are fixed, we can directly using the name.
=> fix(manila): Improve service_instance_security_group

roles/kube_prometheus_stack/files/jsonnet/legacy.libsonnet
Add alerts NodeSoftNetTimesSqueezed and NodeSoftNetBacklogLength
This partially reverts commit 6b7accacd089c740ae2ba92405d32e0e9f64b4dc
fix https://github.com/vexxhost/atmosphere/issues/450
=> Add alerts NodeSoftNetTimesSqueezed and NodeSoftNetBacklogLength

.github/workflows/ceph.yml
It will give a path to jump in to the gh runner instance to troubleshoot the errors of molecule converge whenever we need it.
Put another way, normally it will not create a tmate session to runner instance and run `molecule test` without interruption.
If we need a debug session, we can run the `ceph` workflow manually in a dispatch mode, setting `debug_enabled` value as true.
=> feat(ci): Add a debug job for molecule ceph workflow

galaxy.yml, roles/defaults/defaults/main.yml
by bumping k8s collection version
fix: https://github.com/vexxhost/atmosphere/issues/423 https://github.com/vexxhost/atmosphere/issues/453
depends-on: https://github.com/vexxhost/ansible-collection-kubernetes/pull/26
=> chore: Upgrade cilium version

galaxy.yml, roles/defaults/vars/main.yml
The changes in 1.4 CAPI allow for changing the annotations without causing a full rollout.  We need those fixes in order to be able to deliver a smoother way of managing node groups min/max labels.
=> fix: bump capi to enable smoother autoscaling

roles/defaults/vars/main.yml
This introduce fixes for public subnet.
fix https://github.com/vexxhost/atmosphere/issues/399
So after this fix, only member in admin project (where public network created) can add subnets to `public`
=> Bump images for _atmosphere_images

Earthfile, build/pin-images.py, charts/libvirt/templates/bin/_cert-init.sh.tpl, charts/libvirt/templates/bin/_libvirt.sh.tpl, charts/libvirt/templates/certificate-ca.yaml, charts/libvirt/templates/configmap-bin.yaml, charts/libvirt/templates/daemonset-libvirt.yaml, charts/libvirt/templates/issuer.yaml, charts/libvirt/templates/role-cert-manager.yaml, charts/libvirt/values.yaml, charts/nova/templates/certificate-novnc.yaml, charts/nova/templates/configmap-etc.yaml, charts/nova/templates/deployment-novncproxy.yaml, charts/nova/values.yaml, roles/defaults/vars/main.yml, roles/libvirt/vars/main.yml, roles/nova/vars/main.yml
- chore(libvirt): enable tls cert issuance
- chore(images): add kubectl image
- chore(libvirt): enable tls
- chore(libvirt): revert tls change
- chore(libvirt): refactor to dynamic certs
- chore(libvirt): remove extra colon
- chore(libvirt): add POD_IP and rolebinding
- chore(libvirt): add ca and issuer
- fix: use correct issuer name
- chore: save libvirt certs to pod-tmp
- chore(libvirt): start using certs
- chore: added vnc certs
- chore(libvirt): add secret clean-up
- chore(libvirt): add nova tls support for vnc
- chore(libvirt): enable vencrypt
- chore(libvirt): fix yaml indents
- chore(libvirt): enable tls live migration
- chore(libvirt): switch back to tunnelled
=> feat(libvirt): add tls for vnc+live migration

roles/magnum/README.md, roles/magnum/defaults/main.yml
v1.23 is already at EOL
v1.24.15 is almost to reach it's EOL (2023-07-28)
As we're hitting Ceph space fillup issue, let's remove those support so we can avoid upload images for those deprecated version.
=> Remove old version of kubernetes

roles/nova/vars/main.yml
If a cell is down, OpenStack responds with a 200 OK but the instances
missing when using the older micro-versions.  This is very confusing
for users and most of the time there is only a single cell anyways
that is in place.
It makes sense to just give a 500 error instead, the user will
work much better.
=> fix(nova): set list_records_by_skipping_down_cells to false

roles/openstack_helm_endpoints/vars/main.yml
Many years ago (almost 7!), Nova dropped using the project ID,
which is historically called tenant ID in the service catalog[0].
Let's do the same so that we can make it much easier for users
to take advantage of access rules and be more consistent.
[0]: https://github.com/openstack/devstack/commit/7f87efdd21e92721fe2bf8bb493deb4822e32f1b
=> fix(nova): drop tenant_id from url

.github/workflows/lint.yml
Start using `pre-commit` cache: https://pre-commit.com/#github-actions-example
=> chore(lint): Make initial linting more faster

roles/defaults/vars/main.yml
Keystone is failing because we remove the old build keystone image (sha 8214ccc92d7973451509701c5728d5af614762be3b2b89b29e486f28eb68167f) 
Which block jobs for PRs (like https://github.com/vexxhost/atmosphere/actions/runs/5891949296/job/15980160551?pr=530#step:6:169)
=> chore(keystone): Sync keystone image sha

roles/openstack_exporter/tasks/main.yml
fix https://github.com/vexxhost/atmosphere/issues/534
=> fix: Explict uses 2.87 nova api for openstack_exporter

roles/rook_ceph/vars/main.yml
Fix when using the rook_ceph with local repository.
With path it was only using the path without the DNS name of the image repository.
=> fix: rook_ceph k8s image

charts/glance/templates/pvc-images.yaml, charts/octavia/requirements.lock, hack/sync-charts.sh
Make sure Once PVC glance-images never get deleted.
fix https://github.com/vexxhost/atmosphere/issues/518
=> Use keep as resoruce policy for glance-images

roles/defaults/vars/main.yml
Closes https://github.com/vexxhost/atmosphere/issues/550
- Starting from this tag `libvirtd` build for `aarch64` was introduced.
- `bitnami/kubectl` is using different SHA per platform. Switch to TAG instead of SHA (`1.27.3` is the version which `atmoshere` is using now).
=> feat: introduce aarch64 support for libvirt pod

charts/horizon/Chart.yaml, charts/horizon/charts/helm-toolkit/Chart.yaml, charts/horizon/charts/helm-toolkit/templates/utils/_dependency_resolver.tpl, charts/horizon/requirements.lock, charts/horizon/templates/deployment.yaml, hack/sync-charts.sh
drive-by: Bump horizon chart version from 0.3.8 to 0.3.10
Apply https://review.opendev.org/c/openstack/openstack-helm/+/891987
fix https://github.com/vexxhost/atmosphere/issues/531
=> feat: Rollout horizon deployment whenever logo changed

internal/pkg/image_repositories/build_workflow.go
Since all patches have been merged upstream, there is no longer a need to use the forked repository. To reduce technical debt, we can remove Cinder from the list of forked repositories.
related issue: https://github.com/vexxhost/atmosphere/issues/529
=> chore: Use upstream cinder to build container images

roles/neutron/vars/main.yml
Configure OVN to emit "need to frag" packets in case of MTU mismatch.
fix https://github.com/vexxhost/atmosphere/issues/546
=> Enable ovn_emit_need_to_frag

roles/keystone/vars/main.yml
Fix: add vexxhost.atmosphere when using urlencoded_issuer_from_domain.
=> Fix: urlencoded_issuer_from_domain

roles/keycloak/defaults/main.yml, roles/keycloak/tasks/main.yml
Fix: correct keycloak TLS secret when openstack_helm_ingress_secret_name is used for wildcard-certs.
=> Fix: correct keycloak TLS secret with wildcard-certs

roles/barbican/vars/main.yml, roles/cinder/vars/main.yml, roles/designate/vars/main.yml, roles/glance/vars/main.yml, roles/heat/vars/main.yml, roles/magnum/vars/main.yml, roles/manila/vars/main.yml, roles/neutron/vars/main.yml, roles/nova/vars/main.yml, roles/octavia/vars/main.yml, roles/placement/vars/main.yml, roles/senlin/vars/main.yml
This reverts commit 72f64dc7f1c32b2fc21bf76563d87cd57137de60 as it's no longer required base on @okozachenko1203 's early comments and upstream patch
=> chore: Revert "fix(auth): Define service_type in keystone_authtoken (#411)"

.github/workflows/keycloak.yml
fix https://github.com/vexxhost/atmosphere/issues/613
=> fix: Use a larger runner for keycloak CI jobs

roles/nova/defaults/main.yml, roles/nova/tasks/main.yml, roles/nova/vars/main.yml
Use annotations for nova api and vnc ingresses separately
fix #653
=> fix: Fix VNC times out after 60 seconds of idle time

charts/neutron/templates/bin/_neutron-openvswitch-agent-readiness.sh.tpl
with new OVS installs the ovs-agent does not become ready.  Only applies if you are enabling DPDK
=> fix: OVS 2.15 changed terminology slave to member

roles/ingress_nginx/vars/main.yml
chore: pin ingress-nginx to the control plane to fix #657
=> chore: pin ingress-nginx to the control plane

charts/neutron/templates/bin/_neutron-openvswitch-agent-init.sh.tpl
We had a requirement for our DPDK bonds to have more than one option set during creation.  This change allows a space separated string to be used in the inventory.
```yaml
neutron_helm_values:
conf:
ovs_dpdk:
bonds:
- name: dpdkbond
- ovs_options: 'bond_mode=balance-tcp lacp=active'
...
```
=> fix(ovs): accept space separated string for ovs_options for dpdk bonds

roles/cluster_issuer/tasks/type/ca/main.yml
as the doc says https://github.com/vexxhost/atmosphere/blob/main/roles/cluster_issuer/README.md#using-pre-existing-ca
=> docs: Allow plain certs for CA cluster issuer inventory

hack/sync-charts.sh
Currently staffeln charts still live in Atmosphere. Let's keep this until we seperate it out.
relate to https://github.com/vexxhost/atmosphere/issues/681
=> fix(hack): Avoid remove staffeln charts

roles/octavia/tasks/generate_resources.yml
port 5555 usage should be udp.
For 10514 and 20514, it depends on log_protocol[1].
[1] https://docs.openstack.org/octavia/latest/configuration/configref.html#amphora_agent.log_protocol
fix https://github.com/vexxhost/atmosphere/issues/697
=> fix(octavia): Correct port protocol

charts/ovn/templates/bin/_ovn-controller-init.sh.tpl, charts/ovn/values.yaml
Needing to automatically configure a netdev datapath type for ovn-bridge (default: br-int) for DPDK enabled OVN/OVS
=> fix: configure ovn-bridge with netdev datapath type when dpdk is enabled

Earthfile
python3 is not installed in the base image, this is requered for the +image section for Atmosphere
=> fix: use cloud-archive-base for Atmosphere image

images/openstack-service/Earthfile
zed upperconstraint uses pyOpenSSL===22.0.0 but we need pyOpenSSL>=22.1.0 to avoid bug from pyOpenSSL.
We can remove this line once we move nova to 2023.2
=> fix: update upperconstraint for zed

images/nova/patches/nova/0000-libvirt-Stop-unconditionally-enabling-evmcs.patch, images/nova/patches/nova/0001-libvirt-stop-enabling-hyperv-feature-reenlightenment.patch
Windows VMs are failing to live migrate when setting `os_type` to
`windows` property on images under both Intel and AMD systems due
to a lack of support inside QEMU.
In addition, running Windows VMs on AMD systems is not possible due
to the fact that an unsupported feature tries to get added by default.
This adds two upstream patches which disable both of these and make
it possible to run high performance VMs within OpenStack.
Related-Bug: https://bugs.launchpad.net/nova/+bug/2046549
Related-Bug: https://bugs.launchpad.net/nova/+bug/2009280
=> fix(nova): cherry-pick windows fixes

images/base/Earthfile, images/openstack-service/Earthfile
Building of the images failes with the error `Version '3.0.2-0ubuntu1.14' for 'libssl3' was not found` fixes #993
=> fix: update ubuntu package libssl3

.gitignore, .stestr.conf, atmosphere/tests/roles/test_openvswitch.py, atmosphere/tests/roles/test_ovn.py, flake.nix, test-requirements.txt, tox.ini, zuul.d/jobs.yaml, zuul.d/playbooks/molecule/post.yml, zuul.d/playbooks/molecule/pre.yml, zuul.d/playbooks/molecule/run.yml
We realized that we actually were pointing to the wrong
folder for our database.  This adds tests to make sure
that we verify that the database is at the right place.
Depends-On: https://github.com/vexxhost/atmosphere/pull/1044
=> ci(ovn): add verification tests for database

tox.ini
The debug logs generate a tremendous amount of data which makes
errors cycle out when we collect logs.  Until we solve that, let
us go back to non-DEBUG logs to get more details.
=> ci: disable debug for logs

roles/defaults/vars/main.yml
Fix for:
```
W0403 00:49:34.034468   70448 checks.go:835] detected that the sandbox image "registry.k8s.io/pause:3.8@sha256:f5944f2d1daf66463768a1503d0c8c5e8dde7c1674d3f85abc70cef9c7e32e95" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using "registry.k8s.io/pause:3.9" as the CRI sandbox image.
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
```
=> fix(defaults): Update sandbox image to pause:3.9

charts/cinder/values.yaml, charts/designate/values.yaml, charts/glance/values.yaml, charts/heat/values.yaml, charts/magnum/values.yaml, charts/manila/values.yaml, charts/nova/values.yaml, charts/octavia/values.yaml, charts/placement/values.yaml, charts/senlin/values.yaml
The current uWSGI settings that we ship are missing a few important
ones, specifically `http-raw-body` which is used by Glance in order
to enable chunked uploads.
This is the reason why a direct upload to Glance works just fine
because it goes through the ingress (which does the chunking for
us), however, it fails when creating an image from volume due to
the fact that Cinder talks directly to Glance without the ingress
being in the path.
Closes: #1046
=> fix(uwsgi): tune settings

roles/glance_image/tasks/main.yml
The internet is not reliable.  We instead introduce 3 retries for
downloading images, with a random delay of at least 3 seconds to
make sure we can retry safely.
Depends-On: https://github.com/vexxhost/atmosphere/pull/1063
=> fix(glance_image): introduce retries

zuul.d/playbooks/buildset-registry/run.yml
It seems cosign will always sign an image even if it's already
signed which means we keep getting a new `sha256` everytime we
upload new images.
By changing this behaviour, we only sign the images that are not
signed and avoid changing the SHAs for the images.
=> ci: stop signing images all the time

roles/ipmi_exporter/defaults/main.yml
These sensors are returning false positives on R630/R730xd servers.
=> fix(ipmi-exporter): Ignore additional sensor IDs (BP/Entity Presence)

Earthfile, build/pin-images.py, tox.ini, zuul.d/jobs.yaml, zuul.d/playbooks/build-collection/pre.yml, zuul.d/playbooks/build-collection/publish.yml, zuul.d/playbooks/build-collection/run.yml, zuul.d/secrets.yaml
=> Implement collection release process

zuul.d/container-images/libvirt-tls-sidecar.yaml, zuul.d/container-images/netoffload.yaml
- **build: build all images + run tests using them (#1069)**
- **ci: fix promotion jobs (#1072)**
- **[stable/zed] Drop `conventional-commit` requirement (#1082)**
- **[stable/zed] fix(ipmi-exporter): Ignore additional sensor IDs (BP/Entity Presence) (#1077)**
- **[stable/zed] Implement collection release process (#1085)**
- **Release 1.11.0 (#1088)**
- **Fix dependency for certain images**
=> [stable/zed] fix image job dependencies

roles/defaults/vars/main.yml, roles/kube_prometheus_stack/files/jsonnet/openstack.libsonnet, roles/openstack_exporter/tasks/main.yml
If RabbitMQ decides to go for a nap, some messages may be stuck
and it may cause certain VMs to be stuck in certain states such
as deleting or building.
This adds monitoring in order to catch if any of those operations
are stuck in the cloud.
=> Add monitoring for stuck VMs

roles/rook_ceph/vars/main.yml
~~[Default](https://github.com/vexxhost/atmosphere/blob/main/charts/rook-ceph/values.yaml#L29) is 100m which causes a lot of alert flapping even in a tiny idle cluster.~~
Default CPU limit is 500m which causes alert flapping. Increasing to 1 to accommodate peaks.
Tweaking it in the role so it's easier to sync the chart's values.yml with upstream.
=> Increase rook-ceph-operator CPU limit to 1

roles/loki/vars/main.yml
The default log_level is `info` which causes every query to generate dozens of new log lines with the query's contents which then show up in future results if the query is execute again making it harder to find what you were looking for in the middle of extra noise that has to be filtered out when doing a global search.
=> Change Loki log_level from info to warn

roles/defaults/vars/main.yml
A Ceph cluster deployed with vexxhost.ceph uses Ceph v18.2.1 by default but the `rook_ceph_cluster` role specifies v16.11.2 in the [cephClusterSpec](https://github.com/vexxhost/atmosphere/blob/main/roles/rook_ceph_cluster/vars/main.yml#L17). This has the practical effect of deploying RGW with v16.2.11.
=> Update Ceph image to v18.2.1

doc/source/deploy/glance.rst
https://docs.openstack.org/glance/latest/configuration/glance_api.html#image_format
=> docs/glance: Fix typo in image_format section name for cinder backend

roles/kubernetes_node_labels/tasks/main.yml
In `vexxhost.kubernetes.kubelet` `kubelete_hostname` default value is `inventory_hostname_short`.  But it also can be changed to something else. Let's use proper variable here.
=> fix: use kubelet_hostname instead of inventory_hostname_short

images/glance/Dockerfile, images/ironic/Dockerfile, images/nova/Dockerfile
fix https://github.com/vexxhost/atmosphere/issues/1183
In Ubuntu Jammy, the qemu-block-extra package is no longer required by the qemu-utils package and should be additionally installed to use rbd backend.
Depends-On: https://github.com/vexxhost/atmosphere/pull/1181
=> fix: Install qemu-block-extra in nova, cinder, ironic images

images/glance/Dockerfile, images/horizon/Dockerfile, images/neutron/Dockerfile, images/octavia/Dockerfile
zed is unmaintained and the branch name changed from stable/zed to unmaintained/zed
=> fix(images): change zed branch name

.ansible-lint, galaxy.yml
Also don't add .mypy_cache to galaxy builds (58% of disk usage or 54MB uncompressed).
=> Ignore ansible-lint warnings about storpool files and zuul.d dir

roles/cluster_issuer/defaults/main.yml, roles/cluster_issuer/tasks/main.yml, roles/openstack_cli/templates/atmosphere.sh.j2, roles/openstack_cli/templates/openrc.j2, roles/openstacksdk/templates/clouds.yaml.j2
Related: https://github.com/vexxhost/atmosphere/issues/1185
We disscused with @mpiscaer on Slack about the reason why this happens and found that such a configuration was not foreseen.
Mounting whole directory like here: https://github.com/vexxhost/ansible-collection-kubernetes/blob/main/roles/cert_manager/vars/main.yml#L21 is a bad idea because on EL distros this host path doesn't exist.
=> feat: trust private acme CA

zuul.d/container-images/nova-ssh.yaml
nologin avoids ssh connection between noova-computes which is required for live migrations.
fix https://github.com/vexxhost/atmosphere/issues/1245
=> fix: allow ssh login for nova user in nova-ssh image

roles/prometheus_pushgateway/tasks/main.yml
Reinstall prometheus_pushgateway helm when existing release <2.0.0
Related-To: #1282
Related-To: #1308
=> fix: reinstall prometheus_pushgateway when <2.0.0

roles/kube_prometheus_stack/vars/main.yml
This issue fixes https://github.com/vexxhost/atmosphere/issues/1187
=> fix: add CA mounts in the Prometheus oauth2 container

images/neutron/Dockerfile
This is to bring in the OVN FIP gateway_port support fix.
=> [stable/2023.1] Bump Neutron version

roles/neutron/tasks/main.yml, roles/neutron/vars/main.yml
- Set `_neutron_external_dns_driver` before `__neutron_helm_values` and `__neutron_ovn_helm_values`. In other case it is always omitted.
Even if we set `external_dns_driver` to `designate`: https://opendev.org/openstack/openstack-helm/src/branch/master/neutron/templates/configmap-etc.yaml#L222
There is a bug/typo  upstream which sets Keystone URI to Designate endpoint: https://opendev.org/openstack/openstack-helm/src/branch/master/neutron/templates/configmap-etc.yaml#L239
- Adding auth_url and url accordingly until this will be fixed.
=> fix: neutron designate integration

zuul.d/playbooks/molecule/pre.yml
This should hopefully improve the performance of the
etcd and minimize the amount of of etcdserver timeouts
during CI.
=> Move etcd to ramdisk

roles/neutron/tasks/main.yml, roles/neutron/vars/main.yml
Set _neutron_external_dns_driver before __neutron_helm_values and __neutron_ovn_helm_values. In other case it is always omitted.
Even if we set external_dns_driver to designate: https://opendev.org/openstack/openstack-helm/src/branch/master/neutron/templates/configmap-etc.yaml#L222
There is a bug/typo  upstream which sets Keystone URI to Designate endpoint: https://opendev.org/openstack/openstack-helm/src/branch/master/neutron/templates/configmap-etc.yaml#L239
Adding auth_url and url accordingly until this will be fixed.
=> [stable/zed] fix: neutron designate integration

roles/keystone/vars/main.yml
Thanks @mnaser for showing how to use multistrings for this, much appreciated.
Related: https://github.com/vexxhost/keystoneauth-websso
=> keystone: Add v3websso plugin's localhost URL to trusted_dashboard [ATMOSPHERE-252]

images/neutron/Dockerfile
relate to https://github.com/vexxhost/atmosphere/pull/1458
=> [stable/2023.1] chore: use git ref for neutron-vpnaas

images/neutron/Dockerfile
The cause for this is due to projects are around release cycle that makes the dependency conflict https://github.com/openstack/neutron-vpnaas/commit/f2fcd4586c96e7ff4fa5ca368fbe89cffa55fe7a
this is currently blocking our neutron image build jobs in https://github.com/vexxhost/atmosphere/pull/1428
=> fix: limit neutron vpnaas ref

roles/kube_prometheus_stack/vars/main.yml
Fix for this error:
Logs:
```
logger=user.sync t=2024-07-03T13:21:38.811238068Z level=error msg="Failed to create user" error="user already exists" auth_module=oauth_generic_oauth auth_id=c783731b-55bc-44db-acc3-263924027437
```
This stopped working in >10.1.0 and prevents Grafana from finding existing users by their email when configured to use Keycloak SSO.
https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#enable-email-lookup
=> grafana: Allow user lookups by email

zuul.d/jobs.yaml, zuul.d/playbooks/upgrade/run-upgrade.yml, zuul.d/project.yaml
Relate-to: https://github.com/vexxhost/atmosphere/issues/1068
Relate-to: https://github.com/vexxhost/atmosphere/issues/1282
Depends-On: https://github.com/vexxhost/atmosphere/pull/1408
Depends-On: https://github.com/vexxhost/atmosphere/pull/1409
=> chore: add upgrade job

roles/kube_prometheus_stack/vars/main.yml
=> Fix `libvirt_exporter` missing `namespaceSelector:

images/cinder/Dockerfile, images/glance/Dockerfile, images/nova/Dockerfile
This commit updates  2024.1 stable commit id of Nova,Glance,Cinder Dockerfile to fix OSSA-2024-001 security issue.
=> [stable/2024.1] OSSA-2024-001

images/cinder/Dockerfile, images/glance/Dockerfile, images/nova/Dockerfile
This commit updates  2023.1 stable commit id of Nova,Glance,Cinder Dockerfile to fix OSSA-2024-001 security issue.
=> [stable/2023.1] OSSA-2024-001

images/python-openstackclient/Dockerfile
This fixes the ability to be able to run the CLI anywhere
other than /tmp and also exports the SHELL variable so that
the Magnum clients works happily.
=> Fix CLI issues

charts/ovn/values.yaml, charts/patches/ovn/0003-oci-image-registry-secret.patch
The current values.yaml uses the service name to create separate secrets. However, helm-toolkit indexes into oci_image_registry using .Chart.Name and not $serviceName so the secrets are not used.
Upstream: https://review.opendev.org/c/openstack/openstack-helm-infra/+/923779
Pushing this as a patch until we have it upstream (applied with `tox -e sync-charts`).
=> ovn: Use chart name in oci_image_registry secret

roles/multipathd/tasks/main.yml
=> Fix multipathd ppa install failure in non Ubuntu Jammy release

roles/kube_prometheus_stack/files/jsonnet/openstack.libsonnet
the NovaCapacity it does not take ram_allocation_ratio into account I have hardcoded this at 90%. But U think we can do better
=> fix: nova capacity alert

images/horizon/patches/horizon/0002-normalize-url-join-for-placement.patch
upstream patch: https://review.opendev.org/c/openstack/horizon/+/924729
closes https://github.com/vexxhost/atmosphere/issues/1679
=> [stable/2023.2] fix(horizon): apply a patch to fix resource provider panel 

images/horizon/patches/horizon/0002-normalize-url-join-for-placement.patch
upstream patch: https://review.opendev.org/c/openstack/horizon/+/924729
closes https://github.com/vexxhost/atmosphere/issues/1680
=> [stable/2023.1] fix(horizon): apply a patch to fix resource provider panel #1680

roles/defaults/vars/main.yml, roles/kube_prometheus_stack/defaults/main.yml, roles/kube_prometheus_stack/tasks/main.yml, roles/kube_prometheus_stack/vars/main.yml
- **Initial round of node-tls-sidecar**
- **Fix image name**
- **Added pod-tls-sidecar for node-exporter**
- **The art of escaping Helm and Ansible**
- **Fix configmap mount**
- **Dance around Helm**
- **Fix volume mount**
- **Mount service token**
- **Added RBAC**
- **Fix role binding name**
- **Switch node exporter to use TLS**
- **Fix mount**
- **Switch to VerifyClientCertIfGiven**
=> Add TLS to node exporter

roles/defaults/vars/main.yml, roles/kube_prometheus_stack/defaults/main.yml, roles/kube_prometheus_stack/tasks/main.yml, roles/kube_prometheus_stack/vars/main.yml
This is manual cherry-pick, Fixes #1778
Initial round of node-tls-sidecar
Fix image name
Added pod-tls-sidecar for node-exporter
The art of escaping Helm and Ansible
Fix configmap mount
Dance around Helm
Fix volume mount
Mount service token
Added RBAC
Fix role binding name
Switch node exporter to use TLS
Fix mount
Switch to VerifyClientCertIfGiven
=> [stable/zed] Add TLS to node exporter

roles/ingress_nginx/vars/main.yml
Set the wait up from default 300s to 30s for the drain of ingress connections.
Depends-On: https://github.com/vexxhost/atmosphere/pull/1791
=> [ATMOSPHERE-390] Reduce the ingress controller grace shutdown period

roles/ingress_nginx/vars/main.yml
Set the wait up from default 300s to 30s for the drain of ingress connections. 
(cherry picked from commit 1d7285b013f6c515d0c2537bf418967b358e78dd)
=> [ATMOSPHERE-392] 2023 1 antelope allow for smoother ingress nginx upgrades

roles/ingress_nginx/vars/main.yml
Set the wait up from default 300s to 30s for the drain of ingress connections.
(cherry picked from commit 1d7285b013f6c515d0c2537bf418967b358e78dd)
=> [ATMOSPHERE-391] zed allow for smoother ingress nginx upgrades

roles/keycloak/tasks/main.yml
At the moment, it seems that we’re not waiting for Keycloak to finish rolling out before we move forward, so the migration can be still be running.
=> [ATMOSPHERE-405] fix: wait until keycloak ready

roles/ingress_nginx/vars/main.yml
Set the wait up from 300s to 10s for the drain of ingress connections. Set nginx worker-shutdown-timeout to 5s from default 240s.
=> [ATMOSPHERE-394] 2023 2 bobcat allow for smoother ingress nginx upgrades

roles/magnum/vars/main.yml
2.15 is minimum version to support soft-* server group policy rule
=> feat: specify api microversion for nova client in magnum conf

playbooks/ceph.yml, roles/rook_ceph_cluster/tasks/main.yml
When rook-ceph deploys daemon outside of cephadm purview, cephadm will trigger a warning about stray daemons, putting the cluster in HEALTH_WARN state.
https://docs.ceph.com/en/latest/cephadm/operations/#cephadm-stray-daemon
=> [ATMOSPHERE-362] generate_workspace: Set mgr/cephadm/warn_on_stray_daemons to false

roles/loki/vars/main.yml
fix https://github.com/vexxhost/atmosphere/issues/490
=> [ATMOSPHERE-103] chore: Add loki rule to delect Nova cell down

zuul.d/container-images/nova.yaml
Login should be enabled for nova resizing or migrating between hypervisors [1].
[1]: https://docs.openstack.org/nova/latest/admin/ssh-configuration.html
=> fix: allow ssh login for nova user in nova image

playbooks/openstack.yml, roles/iscsi/README.md, roles/iscsi/tasks/main.yml
This make sure initiatorname gets properly configured And avoid `GenerateName=yes` that failed Nova on attach cinder volume.
=> [ATMOSPHERE-345] fix: Ensure iscsid starts

roles/loki/vars/main.yml
Currently the containers memcached and memcachedExporter for loki don't use the atmosphere_images variable. This way it is not overwritable.
I have tested this on the zed and 2023.1 branch. This has only been seen on the 2023.1 branch.
=> fix: memcached and memcachedExporter use the atmosphere_images

galaxy.yml, roles/cert_manager/tasks/main.yml, roles/defaults/vars/main.yml
solves airgapped clusters and using ACME certificates, cert PR requires vexxhost/ansible-collection-kubernetes#132
fixes: vexxhost/ansible-collection-containers#29
=> fix: add acmesolver for airgapped clusters

images/ironic/Dockerfile
Bump to latest ironic stable/2024.1 to fix CVE-2024-44082
=> [ATMOSPHERE-444] ironic unvalidated image data passed to qemu img CVE 2024 44082

roles/rook_ceph_cluster/vars/main.yml
Currently we are using external ceph cluster, so ceph exporter service managed by rook operator is useless to collect k8s ceph metrics.
=> fix: disable ceph exporter managed by rook operator

roles/loki/vars/main.yml
Fixes #525 Adds the following config
ref: https://grafana.com/docs/loki/latest/operations/storage/retention/
limits_config:
retention_period: 30d # Keep 30 days
compactor:
delete_request_cancel_period: 10m # don't wait 24h before processing the delete_request
retention_enabled: true # enable log retention
retention_delete_delay: 2h # wait 2 hours before actually deleting stuff
=> [ATMOSPHERE-116] Support loki log rotation

roles/loki/vars/main.yml
Enable loki log rotation by default, the default retention period is 30 days.
Fixes #525
=> [ATMOSPHERE-465]  add log rotation for loki

roles/loki/vars/main.yml
Enable loki log rotation by default, the default retention period is 30 days.
Fixes #525
=> [ATMOSPHERE-464] Support loki log rotation

roles/loki/vars/main.yml
Enable loki log rotation by default, the default retention period is 30 days.
Fixes #525
=> [ATMOSPHERE-466] Support loki log rotation

roles/loki/vars/main.yml
Enable loki log rotation by default, the default retention period is 30 days.
Fixes #525
=> [ATMOSPHERE-467] Support loki log rotation

roles/rook_ceph_cluster/vars/main.yml
Currently we are using external ceph cluster, so ceph exporter service managed by rook operator is useless to collect k8s ceph metrics.
=> [ATMOSPHERE-455] fix: disable ceph exporter managed by rook operator (#1896)

roles/rook_ceph_cluster/vars/main.yml
Currently we are using external ceph cluster, so ceph exporter service managed by rook operator is useless to collect k8s ceph metrics.
=> [ATMOSPHERE-456] fix: disable ceph exporter managed by rook operator (#1896)

roles/rook_ceph_cluster/vars/main.yml
Currently we are using external ceph cluster, so ceph exporter service managed by rook operator is useless to collect k8s ceph metrics.
=> [ATMOSPHERE-457] fix: disable ceph exporter managed by rook operator (#1896)

roles/percona_xtradb_cluster/vars/main.yml
Since we are now using version 1.14.0 of the operator and default haproxy tag from it is also 1.14.0 we need to update haproxy config to `new` version. Without kubernetes resolver startup of haproxy pods takes much longer. And yes, it has nothing to do with crVersion: "1.13.0" from spec itself:)
=> fix: perconas haproxy default cfg

images/ovn/Dockerfile, zuul.d/container-images/ovn.yaml
Reverts vexxhost/atmosphere#2024
```
2024-10-25T21:20:08.132Z|00617|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (Permission denied)
2024-10-25T21:20:16.133Z|00618|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (Permission denied)
2024-10-25T21:20:16.134Z|00619|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (Permission denied)
2024-10-25T21:20:24.136Z|00620|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (Permission denied)
2024-10-25T21:20:24.136Z|00621|rconn|WARN|unix:/var/run/openvswitch/br-int.mgmt: connection failed (Permission denied)
```
=> Revert "[ATMOSPHERE-498]add user and group to ovn container image to rebuild for dpdk file ac…"

roles/ovn/tasks/main.yml, roles/ovn/vars/main.yml
we used to keep `type: hv|gw` labels in ovn-controller and ovn-controller-gw daemonsents to distinguish them.
in the PR #2023, we removed ovn-controller-gw daemonset and keep only one DS to sync with upstream as much as possible. so `type: xx` label is unnecessary. But we cannot remove it for running clouds because `spec.selector` field is immutable.
this pr reverts that label for backward compatibility.
=> [ATMOSPHERE-514] fix ovn for backward compatibility

molecule/aio/group_vars/all/molecule.yml, roles/magnum/defaults/main.yml, roles/magnum/vars/main.yml
also update molecule magnum to use latest 1.31.1 k8s image
=> [ATMOSPHERE-485] update magnum images to  1.29.6 1.30.2 1.31.1

charts/charts_test.go, internal/testutils/oslo_db.go, roles/defaults/vars.go, roles/defaults/vars_test.go, roles/percona_xtradb_cluster/vars_test.go, roles/placement/vars/main.yml, zuul.d/jobs.yaml, zuul.d/project.yaml
- remove 1.22 from `TestKubeconform` test (`node-feature-discovery` uses grpc in probe which is available since 1.22)
- add a workaround values in `TestKubeconform` for loki chart
- skip `CephFilesystemSubVolumeGroup` kind for ceph chart
- fix `oslo_db` test expected values
- update `TestImageExist` test to support image tags without digest
- fix pxc test codes
- supplement placement chart value for database max_retries param
depends-on: https://github.com/vexxhost/atmosphere/pull/1977 
depends-on: https://github.com/vexxhost/atmosphere/pull/1211
depends-on: https://github.com/vexxhost/atmosphere/pull/1987 https://github.com/vexxhost/atmosphere/pull/1211 #1977
=> [ATMOSPHERE-533] ci: update go unit tests

.charts.yml, charts/keystone/Chart.yaml, charts/keystone/templates/bin/_cred-clean.py.tpl, charts/keystone/templates/bin/_endpoint-update.py.tpl, charts/keystone/values.yaml
https://review.opendev.org/c/openstack/openstack-helm/+/934703/
=> [ATMOSPHERE-584] Fix the number of max active fernet keys in Keystone

images/octavia/Dockerfile, images/octavia/patches/octavia/0000-Print-error-when-failed-to-load-pkcs12.patch
https://opendev.org/openstack/octavia/commit/0ad935c7aa679f764d11d692c613aee939a508bc this commit was not backported to zed in upstream because it is unmaintained
=> [ATMOSPHERE-543] [stable/zed] log warning when failed to load pkcs12 cert 

images/nova/Dockerfile
=> [stable/2023.2]chore: bump nova scheduler filters to skip failure domain checks

images/nova/Dockerfile
=> [stable/2023.1]chore: bump nova scheduler filters to skip failure domain checks (#2227)

charts/barbican/templates/bin/_simple_crypto_kek_rewrap.py.tpl, charts/barbican/templates/configmap-etc.yaml, charts/barbican/templates/job-db-drop.yaml, charts/barbican/templates/job-db-init.yaml, charts/manila/templates/job-db-drop.yaml, charts/patches/0001-fix-Use-more-standard-configs-for-staffeln-DBdropjob.patch, charts/patches/barbican/0002-Use-more-standard-configs-for-DBs.patch, charts/patches/manila/0002-Use-more-standard-configs-for-DBs.patch, charts/staffeln/templates/job-db-drop.yaml
Improve DB configs for Barbican and Manila.
Ref from https://github.com/vexxhost/atmosphere/pull/2263
Also push to  https://review.opendev.org/c/openstack/openstack-helm/+/938638
=> fix: Use more standard configs for DBs

roles/kube_prometheus_stack/files/jsonnet/mixins.libsonnet, roles/kube_prometheus_stack/files/jsonnet/tests.yml
Due to MySQLDown being very noisy even the mysql cluster still running above minimal replication, so we need to enhance it 
this pr will replace the `MySQLDown` with `MysqlClusterDown`, `MysqlClusterDown` have two severity P3(warning) and P5(info). i.e when we have 5 percona-xtradb and only 1 replication down it only trigger `MysqlClusterDown` with P5 because the mysql cluster still can operational normally but if we lost 3 replication(which means there only 2 replication) it will trigger `MysqlClusterDown` with P3 since mysql cluster unable to operate
=> Enhance `MySQLDown` alert

.pre-commit-config.yaml
(cherry picked from commit 3f6b4cdfb24890f9d73c4182d95bcff465effa8b) 
(cherry picked from commit 6ff9c3d0d704ad90de6fdd985ed5f8b785c63962)
=> fix lintner job to exclude github actions directory

.pre-commit-config.yaml
(cherry picked from commit 3f6b4cdfb24890f9d73c4182d95bcff465effa8b)
=> fix lintner job to exclude github actions directory 

.charts.yml, .github/styles/config/vocabularies/Base/accept.txt, charts/barbican/templates/bin/_simple_crypto_kek_rewrap.py.tpl, releasenotes/notes/improve-barbican-kek-db-session-92ae79da699adc6d.yaml
Allow using nested transaction if db session already starts root transaction. Check if DB transaction already starts in barbican kek rewrap. And use nested transaction if DB session already starts it's root transaction.
related: https://github.com/vexxhost/atmosphere/issues/2492
Change-Id: I829698ad55011c1a429920d85eb29f7de9e30e0b
=> Check transaction before begin

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml, roles/percona_xtradb_cluster/vars/main.yml, roles/percona_xtradb_cluster/vars_test.go
This change max_allowed_packet to honor new default value since mysql 8.x.
ref https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html
Change-Id: Iebe04b21cedad7c793f84c1e43f13d18a9789b75
=> Bump max_allowed_packet to 64M

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/fix-manila-multiattach-f86725dc81792a28.yaml, roles/manila/vars/main.yml
Bump nova microversion in manila to support multiattach feature. Also use internalURL instead of publicURL to keep manila-nova communication in internal.
Change-Id: I11fdc56abbabdac6b660fe6521ad74eb2027f089
=> [stable/2024.1]Fix manila multiattach

.github/styles/config/vocabularies/Base/accept.txt, .vale.ini, releasenotes/notes/fix-manila-multiattach-f86725dc81792a28.yaml, roles/manila/vars/main.yml
Bump nova microversion in manila to support multiattach feature. Also use internalURL instead of publicURL to keep manila-nova communication in internal.
Change-Id: I11fdc56abbabdac6b660fe6521ad74eb2027f089
=> [stable/zed]Fix manila multiattach

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/fix-manila-multiattach-f86725dc81792a28.yaml, roles/manila/vars/main.yml
Bump nova microversion in manila to support multiattach feature. Also use internalURL instead of publicURL to keep manila-nova communication in internal.
Change-Id: I11fdc56abbabdac6b660fe6521ad74eb2027f089
=> [stable/2024.2]Fix manila multiattach

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml, roles/percona_xtradb_cluster/vars/main.yml, roles/percona_xtradb_cluster/vars_test.go
Backport from https://github.com/vexxhost/atmosphere/pull/2546
Change-Id: Ibb2a18d1e3744b22abbd61f86b7d4a43cfa790c8
=> [stable/2024.1] Drop max_allowed_packet config

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml, roles/percona_xtradb_cluster/vars/main.yml, roles/percona_xtradb_cluster/vars_test.go
Backport from https://github.com/vexxhost/atmosphere/pull/2546
Change-Id: Ibb2a18d1e3744b22abbd61f86b7d4a43cfa790c8
=> [stable/2023.2] Drop max_allowed_packet config

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/honor-defult-max_allowed_packet-5c583ddeebcea7b4.yaml, roles/percona_xtradb_cluster/vars/main.yml, roles/percona_xtradb_cluster/vars_test.go
Backport from https://github.com/vexxhost/atmosphere/pull/2546
Change-Id: Ibb2a18d1e3744b22abbd61f86b7d4a43cfa790c8
=> [stable/2024.2] Drop max_allowed_packet config

.github/styles/config/vocabularies/Base/accept.txt, molecule/aio/prepare.yml, playbooks/csi.yml, playbooks/openstack.yml, releasenotes/notes/enable-auth-token-cache-in-rook-9e15863e87fbe4ba.yaml, roles/defaults/vars/main.yml, roles/rook_ceph_cluster/vars/main.yml
(cherry picked from commit 31544c7ac36b9724302f8e8b3fe2f9cb86c3610c)
=> feat: enable auth token cache in rook (#2653)

releasenotes/notes/Fix-cinder-auth-type-9ea017879a578f2a.yaml, roles/nova/vars/main.yml
[stable/2023.1]add missing cinder.auth_type
Change-Id: Idfa71708a45c1a3db9115601ba580432883cbbec
Signed-off-by: ricolin <rlin@vexxhost.com>
=> [stable/2023.1]add missing cinder.auth_type

releasenotes/notes/Fix-cinder-auth-type-9ea017879a578f2a.yaml, roles/nova/vars/main.yml
[stable/zed]add missing cinder.auth_type
Change-Id: Idfa71708a45c1a3db9115601ba580432883cbbec
Signed-off-by: ricolin <rlin@vexxhost.com>
=> [stable/zed]add missing cinder.auth_type

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/bump-portworx-csi-2fa5859c1e5cb901.yaml, roles/portworx/templates/portworx.yml, roles/portworx/templates/storage_cluster.yml
(cherry picked from commit bd40b10419417c9e992cd8dcb83693a44504442d) (cherry picked from commit 0a86143ee653ee2d871796e7080ca3c57542528c)
=> [Backport stable/2023.1]chore: upgrade portworx csi operator to latest stable (#2798)

.charts.yml, .github/styles/config/vocabularies/Base/accept.txt, charts/nova/values.yaml, releasenotes/notes/fix-cinder-auth-in-nova-adead5a3a276781a.yaml, roles/nova/vars/main.yml
(cherry picked from commit 07775611842d7c0ab09ea915cd9555fad81f2a3a)
=> [Backport stable/2024.1]Fix cinder auth in nova conf (#2805)

.charts.yml, .github/styles/config/vocabularies/Base/accept.txt, charts/nova/values.yaml, releasenotes/notes/fix-cinder-auth-in-nova-adead5a3a276781a.yaml, roles/nova/vars/main.yml
(cherry picked from commit 07775611842d7c0ab09ea915cd9555fad81f2a3a)
=> [Backport stable/2023.2]Fix cinder auth in nova conf (#2805)

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/fix-ca-bundle-path-d33352911b65e755.yaml, roles/defaults/defaults/main.yml, roles/openstack_cli/templates/atmosphere.sh.j2
```
[root@controller2 ~]# head -5 /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
-----BEGIN TRUSTED CERTIFICATE-----
MIIDyzCCArOgAwIBAgIDFE3kMA0GCSqGSIb3DQEBBQUAMIGLMQswCQYDVQQGEwJB
VDFIMEYGA1UECgw/QS1UcnVzdCBHZXMuIGYuIFNpY2hlcmhlaXRzc3lzdGVtZSBp
bSBlbGVrdHIuIERhdGVudmVya2VociBHbWJIMRgwFgYDVQQLDA9BLVRydXN0LVF1
```
```
[root@controller2 ~]# head -5 /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
-----BEGIN CERTIFICATE-----
MIIH0zCCBbugAwIBAgIIXsO3pkN/pOAwDQYJKoZIhvcNAQEFBQAwQjESMBAGA1UE
AwwJQUNDVlJBSVoxMRAwDgYDVQQLDAdQS0lBQ0NWMQ0wCwYDVQQKDARBQ0NWMQsw
CQYDVQQGEwJFUzAeFw0xMTA1MDUwOTM3MzdaFw0zMDEyMzEwOTM3MzdaMEIxEjAQ
```
=> fix: ca bundle path for EL family

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/fix-ca-bundle-path-d33352911b65e755.yaml, roles/defaults/defaults/main.yml, roles/openstack_cli/templates/atmosphere.sh.j2
(cherry picked from commit ac46d25f93e8d3dde029310672ee11bcb8065705)
=> [Backport stable/2023.1] fix: ca bundle path for EL family (#3051)

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/fix-ca-bundle-path-d33352911b65e755.yaml, roles/defaults/defaults/main.yml, roles/openstack_cli/templates/atmosphere.sh.j2
(cherry picked from commit ac46d25f93e8d3dde029310672ee11bcb8065705)
=> [Backport stable/2024.2] fix: ca bundle path for EL family (#3051)

.github/styles/config/vocabularies/Base/accept.txt, releasenotes/notes/fix-ca-bundle-path-d33352911b65e755.yaml, roles/defaults/defaults/main.yml, roles/openstack_cli/templates/atmosphere.sh.j2
(cherry picked from commit ac46d25f93e8d3dde029310672ee11bcb8065705)
=> [Backport stable/2023.2] fix: ca bundle path for EL family (#3051)
